// Package proto contains generated protobuf types.
// This file is a placeholder - run 'make proto' to generate actual types.
package proto

// Envelope is the wire format wrapper (placeholder).
// Run 'make proto' to generate from proto/snmpproxy.proto.
type Envelope struct {
	Id      uint64
	Payload interface{}
}

// GetAuth returns nil (placeholder).
func (e *Envelope) GetAuth() *AuthRequest { return nil }

// GetSample returns nil (placeholder).
func (e *Envelope) GetSample() *Sample { return nil }

// GetError returns nil (placeholder).
func (e *Envelope) GetError() *Error { return nil }

// Envelope_Error wraps an error payload.
type Envelope_Error struct {
	Error *Error
}

// Error represents an error message.
type Error struct {
	Code    int32
	Message string
}

// AuthRequest is a placeholder.
type AuthRequest struct {
	Token string
}

// Sample is a placeholder.
type Sample struct {
	TargetId    string
	TimestampMs int64
	Counter     uint64
	Text        string
	Valid       bool
	Error       string
	PollMs      int32
}

// NOTE: This is a PLACEHOLDER file.
// The actual protobuf types should be generated by running:
//   make proto
// This will compile proto/snmpproxy.proto into proper Go types.
