// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: snmpproxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Request/Response correlation. Push messages use id=0.
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Auth
	//	*Envelope_Monitor
	//	*Envelope_Unmonitor
	//	*Envelope_ListTargets
	//	*Envelope_GetTarget
	//	*Envelope_GetHistory
	//	*Envelope_Subscribe
	//	*Envelope_Unsubscribe
	//	*Envelope_AuthResp
	//	*Envelope_MonitorResp
	//	*Envelope_UnmonitorResp
	//	*Envelope_ListTargetsResp
	//	*Envelope_GetTargetResp
	//	*Envelope_GetHistoryResp
	//	*Envelope_SubscribeResp
	//	*Envelope_UnsubscribeResp
	//	*Envelope_Sample
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_snmpproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetAuth() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *Envelope) GetMonitor() *MonitorRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Monitor); ok {
			return x.Monitor
		}
	}
	return nil
}

func (x *Envelope) GetUnmonitor() *UnmonitorRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Unmonitor); ok {
			return x.Unmonitor
		}
	}
	return nil
}

func (x *Envelope) GetListTargets() *ListTargetsRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ListTargets); ok {
			return x.ListTargets
		}
	}
	return nil
}

func (x *Envelope) GetGetTarget() *GetTargetRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetTarget); ok {
			return x.GetTarget
		}
	}
	return nil
}

func (x *Envelope) GetGetHistory() *GetHistoryRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetHistory); ok {
			return x.GetHistory
		}
	}
	return nil
}

func (x *Envelope) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Envelope) GetUnsubscribe() *UnsubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *Envelope) GetAuthResp() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthResp); ok {
			return x.AuthResp
		}
	}
	return nil
}

func (x *Envelope) GetMonitorResp() *MonitorResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MonitorResp); ok {
			return x.MonitorResp
		}
	}
	return nil
}

func (x *Envelope) GetUnmonitorResp() *UnmonitorResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UnmonitorResp); ok {
			return x.UnmonitorResp
		}
	}
	return nil
}

func (x *Envelope) GetListTargetsResp() *ListTargetsResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ListTargetsResp); ok {
			return x.ListTargetsResp
		}
	}
	return nil
}

func (x *Envelope) GetGetTargetResp() *GetTargetResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetTargetResp); ok {
			return x.GetTargetResp
		}
	}
	return nil
}

func (x *Envelope) GetGetHistoryResp() *GetHistoryResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetHistoryResp); ok {
			return x.GetHistoryResp
		}
	}
	return nil
}

func (x *Envelope) GetSubscribeResp() *SubscribeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SubscribeResp); ok {
			return x.SubscribeResp
		}
	}
	return nil
}

func (x *Envelope) GetUnsubscribeResp() *UnsubscribeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UnsubscribeResp); ok {
			return x.UnsubscribeResp
		}
	}
	return nil
}

func (x *Envelope) GetSample() *Sample {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Sample); ok {
			return x.Sample
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Auth struct {
	// Client → Server
	Auth *AuthRequest `protobuf:"bytes,10,opt,name=auth,proto3,oneof"`
}

type Envelope_Monitor struct {
	Monitor *MonitorRequest `protobuf:"bytes,11,opt,name=monitor,proto3,oneof"`
}

type Envelope_Unmonitor struct {
	Unmonitor *UnmonitorRequest `protobuf:"bytes,12,opt,name=unmonitor,proto3,oneof"`
}

type Envelope_ListTargets struct {
	ListTargets *ListTargetsRequest `protobuf:"bytes,13,opt,name=list_targets,json=listTargets,proto3,oneof"`
}

type Envelope_GetTarget struct {
	GetTarget *GetTargetRequest `protobuf:"bytes,14,opt,name=get_target,json=getTarget,proto3,oneof"`
}

type Envelope_GetHistory struct {
	GetHistory *GetHistoryRequest `protobuf:"bytes,15,opt,name=get_history,json=getHistory,proto3,oneof"`
}

type Envelope_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,16,opt,name=subscribe,proto3,oneof"`
}

type Envelope_Unsubscribe struct {
	Unsubscribe *UnsubscribeRequest `protobuf:"bytes,17,opt,name=unsubscribe,proto3,oneof"`
}

type Envelope_AuthResp struct {
	// Server → Client
	AuthResp *AuthResponse `protobuf:"bytes,50,opt,name=auth_resp,json=authResp,proto3,oneof"`
}

type Envelope_MonitorResp struct {
	MonitorResp *MonitorResponse `protobuf:"bytes,51,opt,name=monitor_resp,json=monitorResp,proto3,oneof"`
}

type Envelope_UnmonitorResp struct {
	UnmonitorResp *UnmonitorResponse `protobuf:"bytes,52,opt,name=unmonitor_resp,json=unmonitorResp,proto3,oneof"`
}

type Envelope_ListTargetsResp struct {
	ListTargetsResp *ListTargetsResponse `protobuf:"bytes,53,opt,name=list_targets_resp,json=listTargetsResp,proto3,oneof"`
}

type Envelope_GetTargetResp struct {
	GetTargetResp *GetTargetResponse `protobuf:"bytes,54,opt,name=get_target_resp,json=getTargetResp,proto3,oneof"`
}

type Envelope_GetHistoryResp struct {
	GetHistoryResp *GetHistoryResponse `protobuf:"bytes,55,opt,name=get_history_resp,json=getHistoryResp,proto3,oneof"`
}

type Envelope_SubscribeResp struct {
	SubscribeResp *SubscribeResponse `protobuf:"bytes,56,opt,name=subscribe_resp,json=subscribeResp,proto3,oneof"`
}

type Envelope_UnsubscribeResp struct {
	UnsubscribeResp *UnsubscribeResponse `protobuf:"bytes,57,opt,name=unsubscribe_resp,json=unsubscribeResp,proto3,oneof"`
}

type Envelope_Sample struct {
	// Server → Client (Push, id=0)
	Sample *Sample `protobuf:"bytes,80,opt,name=sample,proto3,oneof"`
}

type Envelope_Error struct {
	// Server → Client (Error response)
	Error *Error `protobuf:"bytes,99,opt,name=error,proto3,oneof"`
}

func (*Envelope_Auth) isEnvelope_Payload() {}

func (*Envelope_Monitor) isEnvelope_Payload() {}

func (*Envelope_Unmonitor) isEnvelope_Payload() {}

func (*Envelope_ListTargets) isEnvelope_Payload() {}

func (*Envelope_GetTarget) isEnvelope_Payload() {}

func (*Envelope_GetHistory) isEnvelope_Payload() {}

func (*Envelope_Subscribe) isEnvelope_Payload() {}

func (*Envelope_Unsubscribe) isEnvelope_Payload() {}

func (*Envelope_AuthResp) isEnvelope_Payload() {}

func (*Envelope_MonitorResp) isEnvelope_Payload() {}

func (*Envelope_UnmonitorResp) isEnvelope_Payload() {}

func (*Envelope_ListTargetsResp) isEnvelope_Payload() {}

func (*Envelope_GetTargetResp) isEnvelope_Payload() {}

func (*Envelope_GetHistoryResp) isEnvelope_Payload() {}

func (*Envelope_SubscribeResp) isEnvelope_Payload() {}

func (*Envelope_UnsubscribeResp) isEnvelope_Payload() {}

func (*Envelope_Sample) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_snmpproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Counter       uint64                 `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Valid         bool                   `protobuf:"varint,5,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	PollMs        int32                  `protobuf:"varint,7,opt,name=poll_ms,json=pollMs,proto3" json:"poll_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_snmpproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{2}
}

func (x *Sample) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Sample) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Sample) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *Sample) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Sample) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *Sample) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Sample) GetPollMs() int32 {
	if x != nil {
		return x.PollMs
	}
	return 0
}

type SNMPv2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     string                 `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNMPv2C) Reset() {
	*x = SNMPv2C{}
	mi := &file_snmpproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNMPv2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNMPv2C) ProtoMessage() {}

func (x *SNMPv2C) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNMPv2C.ProtoReflect.Descriptor instead.
func (*SNMPv2C) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{3}
}

func (x *SNMPv2C) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

type SNMPv3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecurityName  string                 `protobuf:"bytes,1,opt,name=security_name,json=securityName,proto3" json:"security_name,omitempty"`
	AuthProtocol  string                 `protobuf:"bytes,2,opt,name=auth_protocol,json=authProtocol,proto3" json:"auth_protocol,omitempty"` // "MD5", "SHA", "SHA256", "SHA512"
	AuthPassword  string                 `protobuf:"bytes,3,opt,name=auth_password,json=authPassword,proto3" json:"auth_password,omitempty"`
	PrivProtocol  string                 `protobuf:"bytes,4,opt,name=priv_protocol,json=privProtocol,proto3" json:"priv_protocol,omitempty"` // "DES", "AES", "AES192", "AES256"
	PrivPassword  string                 `protobuf:"bytes,5,opt,name=priv_password,json=privPassword,proto3" json:"priv_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNMPv3) Reset() {
	*x = SNMPv3{}
	mi := &file_snmpproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNMPv3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNMPv3) ProtoMessage() {}

func (x *SNMPv3) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNMPv3.ProtoReflect.Descriptor instead.
func (*SNMPv3) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{4}
}

func (x *SNMPv3) GetSecurityName() string {
	if x != nil {
		return x.SecurityName
	}
	return ""
}

func (x *SNMPv3) GetAuthProtocol() string {
	if x != nil {
		return x.AuthProtocol
	}
	return ""
}

func (x *SNMPv3) GetAuthPassword() string {
	if x != nil {
		return x.AuthPassword
	}
	return ""
}

func (x *SNMPv3) GetPrivProtocol() string {
	if x != nil {
		return x.PrivProtocol
	}
	return ""
}

func (x *SNMPv3) GetPrivPassword() string {
	if x != nil {
		return x.PrivPassword
	}
	return ""
}

type SNMPConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*SNMPConfig_V2C
	//	*SNMPConfig_V3
	Version       isSNMPConfig_Version `protobuf_oneof:"version"`
	TimeoutMs     uint32               `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Retries       uint32               `protobuf:"varint,4,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNMPConfig) Reset() {
	*x = SNMPConfig{}
	mi := &file_snmpproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNMPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNMPConfig) ProtoMessage() {}

func (x *SNMPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNMPConfig.ProtoReflect.Descriptor instead.
func (*SNMPConfig) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{5}
}

func (x *SNMPConfig) GetVersion() isSNMPConfig_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *SNMPConfig) GetV2C() *SNMPv2C {
	if x != nil {
		if x, ok := x.Version.(*SNMPConfig_V2C); ok {
			return x.V2C
		}
	}
	return nil
}

func (x *SNMPConfig) GetV3() *SNMPv3 {
	if x != nil {
		if x, ok := x.Version.(*SNMPConfig_V3); ok {
			return x.V3
		}
	}
	return nil
}

func (x *SNMPConfig) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *SNMPConfig) GetRetries() uint32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

type isSNMPConfig_Version interface {
	isSNMPConfig_Version()
}

type SNMPConfig_V2C struct {
	V2C *SNMPv2C `protobuf:"bytes,1,opt,name=v2c,proto3,oneof"`
}

type SNMPConfig_V3 struct {
	V3 *SNMPv3 `protobuf:"bytes,2,opt,name=v3,proto3,oneof"`
}

func (*SNMPConfig_V2C) isSNMPConfig_Version() {}

func (*SNMPConfig_V3) isSNMPConfig_Version() {}

type Target struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host       string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port       uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Oid        string                 `protobuf:"bytes,4,opt,name=oid,proto3" json:"oid,omitempty"`
	IntervalMs uint32                 `protobuf:"varint,5,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	BufferSize uint32                 `protobuf:"varint,6,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	// Runtime state
	State           string `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"` // "polling", "unreachable", "error"
	LastPollMs      int64  `protobuf:"varint,11,opt,name=last_poll_ms,json=lastPollMs,proto3" json:"last_poll_ms,omitempty"`
	LastError       string `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Subscribers     int32  `protobuf:"varint,13,opt,name=subscribers,proto3" json:"subscribers,omitempty"`
	SamplesBuffered int32  `protobuf:"varint,14,opt,name=samples_buffered,json=samplesBuffered,proto3" json:"samples_buffered,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_snmpproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{6}
}

func (x *Target) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Target) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Target) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Target) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *Target) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *Target) GetBufferSize() uint32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *Target) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Target) GetLastPollMs() int64 {
	if x != nil {
		return x.LastPollMs
	}
	return 0
}

func (x *Target) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Target) GetSubscribers() int32 {
	if x != nil {
		return x.Subscribers
	}
	return 0
}

func (x *Target) GetSamplesBuffered() int32 {
	if x != nil {
		return x.SamplesBuffered
	}
	return 0
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_snmpproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{7}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_snmpproxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{8}
}

func (x *AuthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // Default: 161
	Oid           string                 `protobuf:"bytes,3,opt,name=oid,proto3" json:"oid,omitempty"`
	IntervalMs    uint32                 `protobuf:"varint,4,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // Default: 1000
	BufferSize    uint32                 `protobuf:"varint,5,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"` // Default: 3600
	Snmp          *SNMPConfig            `protobuf:"bytes,6,opt,name=snmp,proto3" json:"snmp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorRequest) Reset() {
	*x = MonitorRequest{}
	mi := &file_snmpproxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorRequest) ProtoMessage() {}

func (x *MonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorRequest.ProtoReflect.Descriptor instead.
func (*MonitorRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{9}
}

func (x *MonitorRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MonitorRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MonitorRequest) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *MonitorRequest) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *MonitorRequest) GetBufferSize() uint32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *MonitorRequest) GetSnmp() *SNMPConfig {
	if x != nil {
		return x.Snmp
	}
	return nil
}

type MonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"` // true if new, false if joined existing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorResponse) Reset() {
	*x = MonitorResponse{}
	mi := &file_snmpproxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorResponse) ProtoMessage() {}

func (x *MonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorResponse.ProtoReflect.Descriptor instead.
func (*MonitorResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{10}
}

func (x *MonitorResponse) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *MonitorResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type UnmonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmonitorRequest) Reset() {
	*x = UnmonitorRequest{}
	mi := &file_snmpproxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmonitorRequest) ProtoMessage() {}

func (x *UnmonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmonitorRequest.ProtoReflect.Descriptor instead.
func (*UnmonitorRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{11}
}

func (x *UnmonitorRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type UnmonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmonitorResponse) Reset() {
	*x = UnmonitorResponse{}
	mi := &file_snmpproxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmonitorResponse) ProtoMessage() {}

func (x *UnmonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmonitorResponse.ProtoReflect.Descriptor instead.
func (*UnmonitorResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{12}
}

func (x *UnmonitorResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListTargetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterHost    string                 `protobuf:"bytes,1,opt,name=filter_host,json=filterHost,proto3" json:"filter_host,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTargetsRequest) Reset() {
	*x = ListTargetsRequest{}
	mi := &file_snmpproxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetsRequest) ProtoMessage() {}

func (x *ListTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTargetsRequest.ProtoReflect.Descriptor instead.
func (*ListTargetsRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{13}
}

func (x *ListTargetsRequest) GetFilterHost() string {
	if x != nil {
		return x.FilterHost
	}
	return ""
}

type ListTargetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*Target              `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTargetsResponse) Reset() {
	*x = ListTargetsResponse{}
	mi := &file_snmpproxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetsResponse) ProtoMessage() {}

func (x *ListTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTargetsResponse.ProtoReflect.Descriptor instead.
func (*ListTargetsResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{14}
}

func (x *ListTargetsResponse) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

type GetTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetRequest) Reset() {
	*x = GetTargetRequest{}
	mi := &file_snmpproxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetRequest) ProtoMessage() {}

func (x *GetTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetRequest.ProtoReflect.Descriptor instead.
func (*GetTargetRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{15}
}

func (x *GetTargetRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type GetTargetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Target                `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetResponse) Reset() {
	*x = GetTargetResponse{}
	mi := &file_snmpproxy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetResponse) ProtoMessage() {}

func (x *GetTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetResponse.ProtoReflect.Descriptor instead.
func (*GetTargetResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{16}
}

func (x *GetTargetResponse) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIds     []string               `protobuf:"bytes,1,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	LastN         uint32                 `protobuf:"varint,2,opt,name=last_n,json=lastN,proto3" json:"last_n,omitempty"` // Number of samples (default: 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_snmpproxy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{17}
}

func (x *GetHistoryRequest) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *GetHistoryRequest) GetLastN() uint32 {
	if x != nil {
		return x.LastN
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*TargetHistory       `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_snmpproxy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{18}
}

func (x *GetHistoryResponse) GetHistory() []*TargetHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type TargetHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Samples       []*Sample              `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetHistory) Reset() {
	*x = TargetHistory{}
	mi := &file_snmpproxy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetHistory) ProtoMessage() {}

func (x *TargetHistory) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetHistory.ProtoReflect.Descriptor instead.
func (*TargetHistory) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{19}
}

func (x *TargetHistory) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *TargetHistory) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIds     []string               `protobuf:"bytes,1,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_snmpproxy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{20}
}

func (x *SubscribeRequest) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Subscribed    []string               `protobuf:"bytes,2,rep,name=subscribed,proto3" json:"subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_snmpproxy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{21}
}

func (x *SubscribeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubscribeResponse) GetSubscribed() []string {
	if x != nil {
		return x.Subscribed
	}
	return nil
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIds     []string               `protobuf:"bytes,1,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"` // Empty = unsubscribe all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_snmpproxy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{22}
}

func (x *UnsubscribeRequest) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_snmpproxy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{23}
}

func (x *UnsubscribeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_snmpproxy_proto protoreflect.FileDescriptor

const file_snmpproxy_proto_rawDesc = "" +
	"\n" +
	"\x0fsnmpproxy.proto\x12\fsnmpproxy.v1\"\xcc\t\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12/\n" +
	"\x04auth\x18\n" +
	" \x01(\v2\x19.snmpproxy.v1.AuthRequestH\x00R\x04auth\x128\n" +
	"\amonitor\x18\v \x01(\v2\x1c.snmpproxy.v1.MonitorRequestH\x00R\amonitor\x12>\n" +
	"\tunmonitor\x18\f \x01(\v2\x1e.snmpproxy.v1.UnmonitorRequestH\x00R\tunmonitor\x12E\n" +
	"\flist_targets\x18\r \x01(\v2 .snmpproxy.v1.ListTargetsRequestH\x00R\vlistTargets\x12?\n" +
	"\n" +
	"get_target\x18\x0e \x01(\v2\x1e.snmpproxy.v1.GetTargetRequestH\x00R\tgetTarget\x12B\n" +
	"\vget_history\x18\x0f \x01(\v2\x1f.snmpproxy.v1.GetHistoryRequestH\x00R\n" +
	"getHistory\x12>\n" +
	"\tsubscribe\x18\x10 \x01(\v2\x1e.snmpproxy.v1.SubscribeRequestH\x00R\tsubscribe\x12D\n" +
	"\vunsubscribe\x18\x11 \x01(\v2 .snmpproxy.v1.UnsubscribeRequestH\x00R\vunsubscribe\x129\n" +
	"\tauth_resp\x182 \x01(\v2\x1a.snmpproxy.v1.AuthResponseH\x00R\bauthResp\x12B\n" +
	"\fmonitor_resp\x183 \x01(\v2\x1d.snmpproxy.v1.MonitorResponseH\x00R\vmonitorResp\x12H\n" +
	"\x0eunmonitor_resp\x184 \x01(\v2\x1f.snmpproxy.v1.UnmonitorResponseH\x00R\runmonitorResp\x12O\n" +
	"\x11list_targets_resp\x185 \x01(\v2!.snmpproxy.v1.ListTargetsResponseH\x00R\x0flistTargetsResp\x12I\n" +
	"\x0fget_target_resp\x186 \x01(\v2\x1f.snmpproxy.v1.GetTargetResponseH\x00R\rgetTargetResp\x12L\n" +
	"\x10get_history_resp\x187 \x01(\v2 .snmpproxy.v1.GetHistoryResponseH\x00R\x0egetHistoryResp\x12H\n" +
	"\x0esubscribe_resp\x188 \x01(\v2\x1f.snmpproxy.v1.SubscribeResponseH\x00R\rsubscribeResp\x12N\n" +
	"\x10unsubscribe_resp\x189 \x01(\v2!.snmpproxy.v1.UnsubscribeResponseH\x00R\x0funsubscribeResp\x12.\n" +
	"\x06sample\x18P \x01(\v2\x14.snmpproxy.v1.SampleH\x00R\x06sample\x12+\n" +
	"\x05error\x18c \x01(\v2\x13.snmpproxy.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x01\n" +
	"\x06Sample\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x18\n" +
	"\acounter\x18\x03 \x01(\x04R\acounter\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05valid\x18\x05 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x17\n" +
	"\apoll_ms\x18\a \x01(\x05R\x06pollMs\"'\n" +
	"\aSNMPv2c\x12\x1c\n" +
	"\tcommunity\x18\x01 \x01(\tR\tcommunity\"\xc1\x01\n" +
	"\x06SNMPv3\x12#\n" +
	"\rsecurity_name\x18\x01 \x01(\tR\fsecurityName\x12#\n" +
	"\rauth_protocol\x18\x02 \x01(\tR\fauthProtocol\x12#\n" +
	"\rauth_password\x18\x03 \x01(\tR\fauthPassword\x12#\n" +
	"\rpriv_protocol\x18\x04 \x01(\tR\fprivProtocol\x12#\n" +
	"\rpriv_password\x18\x05 \x01(\tR\fprivPassword\"\xa3\x01\n" +
	"\n" +
	"SNMPConfig\x12)\n" +
	"\x03v2c\x18\x01 \x01(\v2\x15.snmpproxy.v1.SNMPv2cH\x00R\x03v2c\x12&\n" +
	"\x02v3\x18\x02 \x01(\v2\x14.snmpproxy.v1.SNMPv3H\x00R\x02v3\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\x12\x18\n" +
	"\aretries\x18\x04 \x01(\rR\aretriesB\t\n" +
	"\aversion\"\xb8\x02\n" +
	"\x06Target\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x10\n" +
	"\x03oid\x18\x04 \x01(\tR\x03oid\x12\x1f\n" +
	"\vinterval_ms\x18\x05 \x01(\rR\n" +
	"intervalMs\x12\x1f\n" +
	"\vbuffer_size\x18\x06 \x01(\rR\n" +
	"bufferSize\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12 \n" +
	"\flast_poll_ms\x18\v \x01(\x03R\n" +
	"lastPollMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\x12 \n" +
	"\vsubscribers\x18\r \x01(\x05R\vsubscribers\x12)\n" +
	"\x10samples_buffered\x18\x0e \x01(\x05R\x0fsamplesBuffered\"#\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"W\n" +
	"\fAuthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xba\x01\n" +
	"\x0eMonitorRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x10\n" +
	"\x03oid\x18\x03 \x01(\tR\x03oid\x12\x1f\n" +
	"\vinterval_ms\x18\x04 \x01(\rR\n" +
	"intervalMs\x12\x1f\n" +
	"\vbuffer_size\x18\x05 \x01(\rR\n" +
	"bufferSize\x12,\n" +
	"\x04snmp\x18\x06 \x01(\v2\x18.snmpproxy.v1.SNMPConfigR\x04snmp\"H\n" +
	"\x0fMonitorResponse\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"/\n" +
	"\x10UnmonitorRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"#\n" +
	"\x11UnmonitorResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"5\n" +
	"\x12ListTargetsRequest\x12\x1f\n" +
	"\vfilter_host\x18\x01 \x01(\tR\n" +
	"filterHost\"E\n" +
	"\x13ListTargetsResponse\x12.\n" +
	"\atargets\x18\x01 \x03(\v2\x14.snmpproxy.v1.TargetR\atargets\"/\n" +
	"\x10GetTargetRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"A\n" +
	"\x11GetTargetResponse\x12,\n" +
	"\x06target\x18\x01 \x01(\v2\x14.snmpproxy.v1.TargetR\x06target\"I\n" +
	"\x11GetHistoryRequest\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x01 \x03(\tR\ttargetIds\x12\x15\n" +
	"\x06last_n\x18\x02 \x01(\rR\x05lastN\"K\n" +
	"\x12GetHistoryResponse\x125\n" +
	"\ahistory\x18\x01 \x03(\v2\x1b.snmpproxy.v1.TargetHistoryR\ahistory\"\\\n" +
	"\rTargetHistory\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12.\n" +
	"\asamples\x18\x02 \x03(\v2\x14.snmpproxy.v1.SampleR\asamples\"1\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x01 \x03(\tR\ttargetIds\"C\n" +
	"\x11SubscribeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1e\n" +
	"\n" +
	"subscribed\x18\x02 \x03(\tR\n" +
	"subscribed\"3\n" +
	"\x12UnsubscribeRequest\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x01 \x03(\tR\ttargetIds\"%\n" +
	"\x13UnsubscribeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02okB,Z*github.com/xtxerr/snmpproxy/internal/protob\x06proto3"

var (
	file_snmpproxy_proto_rawDescOnce sync.Once
	file_snmpproxy_proto_rawDescData []byte
)

func file_snmpproxy_proto_rawDescGZIP() []byte {
	file_snmpproxy_proto_rawDescOnce.Do(func() {
		file_snmpproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snmpproxy_proto_rawDesc), len(file_snmpproxy_proto_rawDesc)))
	})
	return file_snmpproxy_proto_rawDescData
}

var file_snmpproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_snmpproxy_proto_goTypes = []any{
	(*Envelope)(nil),            // 0: snmpproxy.v1.Envelope
	(*Error)(nil),               // 1: snmpproxy.v1.Error
	(*Sample)(nil),              // 2: snmpproxy.v1.Sample
	(*SNMPv2C)(nil),             // 3: snmpproxy.v1.SNMPv2c
	(*SNMPv3)(nil),              // 4: snmpproxy.v1.SNMPv3
	(*SNMPConfig)(nil),          // 5: snmpproxy.v1.SNMPConfig
	(*Target)(nil),              // 6: snmpproxy.v1.Target
	(*AuthRequest)(nil),         // 7: snmpproxy.v1.AuthRequest
	(*AuthResponse)(nil),        // 8: snmpproxy.v1.AuthResponse
	(*MonitorRequest)(nil),      // 9: snmpproxy.v1.MonitorRequest
	(*MonitorResponse)(nil),     // 10: snmpproxy.v1.MonitorResponse
	(*UnmonitorRequest)(nil),    // 11: snmpproxy.v1.UnmonitorRequest
	(*UnmonitorResponse)(nil),   // 12: snmpproxy.v1.UnmonitorResponse
	(*ListTargetsRequest)(nil),  // 13: snmpproxy.v1.ListTargetsRequest
	(*ListTargetsResponse)(nil), // 14: snmpproxy.v1.ListTargetsResponse
	(*GetTargetRequest)(nil),    // 15: snmpproxy.v1.GetTargetRequest
	(*GetTargetResponse)(nil),   // 16: snmpproxy.v1.GetTargetResponse
	(*GetHistoryRequest)(nil),   // 17: snmpproxy.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),  // 18: snmpproxy.v1.GetHistoryResponse
	(*TargetHistory)(nil),       // 19: snmpproxy.v1.TargetHistory
	(*SubscribeRequest)(nil),    // 20: snmpproxy.v1.SubscribeRequest
	(*SubscribeResponse)(nil),   // 21: snmpproxy.v1.SubscribeResponse
	(*UnsubscribeRequest)(nil),  // 22: snmpproxy.v1.UnsubscribeRequest
	(*UnsubscribeResponse)(nil), // 23: snmpproxy.v1.UnsubscribeResponse
}
var file_snmpproxy_proto_depIdxs = []int32{
	7,  // 0: snmpproxy.v1.Envelope.auth:type_name -> snmpproxy.v1.AuthRequest
	9,  // 1: snmpproxy.v1.Envelope.monitor:type_name -> snmpproxy.v1.MonitorRequest
	11, // 2: snmpproxy.v1.Envelope.unmonitor:type_name -> snmpproxy.v1.UnmonitorRequest
	13, // 3: snmpproxy.v1.Envelope.list_targets:type_name -> snmpproxy.v1.ListTargetsRequest
	15, // 4: snmpproxy.v1.Envelope.get_target:type_name -> snmpproxy.v1.GetTargetRequest
	17, // 5: snmpproxy.v1.Envelope.get_history:type_name -> snmpproxy.v1.GetHistoryRequest
	20, // 6: snmpproxy.v1.Envelope.subscribe:type_name -> snmpproxy.v1.SubscribeRequest
	22, // 7: snmpproxy.v1.Envelope.unsubscribe:type_name -> snmpproxy.v1.UnsubscribeRequest
	8,  // 8: snmpproxy.v1.Envelope.auth_resp:type_name -> snmpproxy.v1.AuthResponse
	10, // 9: snmpproxy.v1.Envelope.monitor_resp:type_name -> snmpproxy.v1.MonitorResponse
	12, // 10: snmpproxy.v1.Envelope.unmonitor_resp:type_name -> snmpproxy.v1.UnmonitorResponse
	14, // 11: snmpproxy.v1.Envelope.list_targets_resp:type_name -> snmpproxy.v1.ListTargetsResponse
	16, // 12: snmpproxy.v1.Envelope.get_target_resp:type_name -> snmpproxy.v1.GetTargetResponse
	18, // 13: snmpproxy.v1.Envelope.get_history_resp:type_name -> snmpproxy.v1.GetHistoryResponse
	21, // 14: snmpproxy.v1.Envelope.subscribe_resp:type_name -> snmpproxy.v1.SubscribeResponse
	23, // 15: snmpproxy.v1.Envelope.unsubscribe_resp:type_name -> snmpproxy.v1.UnsubscribeResponse
	2,  // 16: snmpproxy.v1.Envelope.sample:type_name -> snmpproxy.v1.Sample
	1,  // 17: snmpproxy.v1.Envelope.error:type_name -> snmpproxy.v1.Error
	3,  // 18: snmpproxy.v1.SNMPConfig.v2c:type_name -> snmpproxy.v1.SNMPv2c
	4,  // 19: snmpproxy.v1.SNMPConfig.v3:type_name -> snmpproxy.v1.SNMPv3
	5,  // 20: snmpproxy.v1.MonitorRequest.snmp:type_name -> snmpproxy.v1.SNMPConfig
	6,  // 21: snmpproxy.v1.ListTargetsResponse.targets:type_name -> snmpproxy.v1.Target
	6,  // 22: snmpproxy.v1.GetTargetResponse.target:type_name -> snmpproxy.v1.Target
	19, // 23: snmpproxy.v1.GetHistoryResponse.history:type_name -> snmpproxy.v1.TargetHistory
	2,  // 24: snmpproxy.v1.TargetHistory.samples:type_name -> snmpproxy.v1.Sample
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_snmpproxy_proto_init() }
func file_snmpproxy_proto_init() {
	if File_snmpproxy_proto != nil {
		return
	}
	file_snmpproxy_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Auth)(nil),
		(*Envelope_Monitor)(nil),
		(*Envelope_Unmonitor)(nil),
		(*Envelope_ListTargets)(nil),
		(*Envelope_GetTarget)(nil),
		(*Envelope_GetHistory)(nil),
		(*Envelope_Subscribe)(nil),
		(*Envelope_Unsubscribe)(nil),
		(*Envelope_AuthResp)(nil),
		(*Envelope_MonitorResp)(nil),
		(*Envelope_UnmonitorResp)(nil),
		(*Envelope_ListTargetsResp)(nil),
		(*Envelope_GetTargetResp)(nil),
		(*Envelope_GetHistoryResp)(nil),
		(*Envelope_SubscribeResp)(nil),
		(*Envelope_UnsubscribeResp)(nil),
		(*Envelope_Sample)(nil),
		(*Envelope_Error)(nil),
	}
	file_snmpproxy_proto_msgTypes[5].OneofWrappers = []any{
		(*SNMPConfig_V2C)(nil),
		(*SNMPConfig_V3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snmpproxy_proto_rawDesc), len(file_snmpproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snmpproxy_proto_goTypes,
		DependencyIndexes: file_snmpproxy_proto_depIdxs,
		MessageInfos:      file_snmpproxy_proto_msgTypes,
	}.Build()
	File_snmpproxy_proto = out.File
	file_snmpproxy_proto_goTypes = nil
	file_snmpproxy_proto_depIdxs = nil
}
