// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: snmpproxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthProtocol int32

const (
	AuthProtocol_AUTH_PROTOCOL_UNSPECIFIED AuthProtocol = 0
	AuthProtocol_AUTH_PROTOCOL_MD5         AuthProtocol = 1
	AuthProtocol_AUTH_PROTOCOL_SHA         AuthProtocol = 2
	AuthProtocol_AUTH_PROTOCOL_SHA224      AuthProtocol = 3
	AuthProtocol_AUTH_PROTOCOL_SHA256      AuthProtocol = 4
	AuthProtocol_AUTH_PROTOCOL_SHA384      AuthProtocol = 5
	AuthProtocol_AUTH_PROTOCOL_SHA512      AuthProtocol = 6
)

// Enum value maps for AuthProtocol.
var (
	AuthProtocol_name = map[int32]string{
		0: "AUTH_PROTOCOL_UNSPECIFIED",
		1: "AUTH_PROTOCOL_MD5",
		2: "AUTH_PROTOCOL_SHA",
		3: "AUTH_PROTOCOL_SHA224",
		4: "AUTH_PROTOCOL_SHA256",
		5: "AUTH_PROTOCOL_SHA384",
		6: "AUTH_PROTOCOL_SHA512",
	}
	AuthProtocol_value = map[string]int32{
		"AUTH_PROTOCOL_UNSPECIFIED": 0,
		"AUTH_PROTOCOL_MD5":         1,
		"AUTH_PROTOCOL_SHA":         2,
		"AUTH_PROTOCOL_SHA224":      3,
		"AUTH_PROTOCOL_SHA256":      4,
		"AUTH_PROTOCOL_SHA384":      5,
		"AUTH_PROTOCOL_SHA512":      6,
	}
)

func (x AuthProtocol) Enum() *AuthProtocol {
	p := new(AuthProtocol)
	*p = x
	return p
}

func (x AuthProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_snmpproxy_proto_enumTypes[0].Descriptor()
}

func (AuthProtocol) Type() protoreflect.EnumType {
	return &file_snmpproxy_proto_enumTypes[0]
}

func (x AuthProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthProtocol.Descriptor instead.
func (AuthProtocol) EnumDescriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{0}
}

type PrivProtocol int32

const (
	PrivProtocol_PRIV_PROTOCOL_UNSPECIFIED PrivProtocol = 0
	PrivProtocol_PRIV_PROTOCOL_DES         PrivProtocol = 1
	PrivProtocol_PRIV_PROTOCOL_AES         PrivProtocol = 2
	PrivProtocol_PRIV_PROTOCOL_AES192      PrivProtocol = 3
	PrivProtocol_PRIV_PROTOCOL_AES256      PrivProtocol = 4
)

// Enum value maps for PrivProtocol.
var (
	PrivProtocol_name = map[int32]string{
		0: "PRIV_PROTOCOL_UNSPECIFIED",
		1: "PRIV_PROTOCOL_DES",
		2: "PRIV_PROTOCOL_AES",
		3: "PRIV_PROTOCOL_AES192",
		4: "PRIV_PROTOCOL_AES256",
	}
	PrivProtocol_value = map[string]int32{
		"PRIV_PROTOCOL_UNSPECIFIED": 0,
		"PRIV_PROTOCOL_DES":         1,
		"PRIV_PROTOCOL_AES":         2,
		"PRIV_PROTOCOL_AES192":      3,
		"PRIV_PROTOCOL_AES256":      4,
	}
)

func (x PrivProtocol) Enum() *PrivProtocol {
	p := new(PrivProtocol)
	*p = x
	return p
}

func (x PrivProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_snmpproxy_proto_enumTypes[1].Descriptor()
}

func (PrivProtocol) Type() protoreflect.EnumType {
	return &file_snmpproxy_proto_enumTypes[1]
}

func (x PrivProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrivProtocol.Descriptor instead.
func (PrivProtocol) EnumDescriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{1}
}

type SecurityLevel int32

const (
	SecurityLevel_SECURITY_LEVEL_UNSPECIFIED     SecurityLevel = 0
	SecurityLevel_SECURITY_LEVEL_NO_AUTH_NO_PRIV SecurityLevel = 1
	SecurityLevel_SECURITY_LEVEL_AUTH_NO_PRIV    SecurityLevel = 2
	SecurityLevel_SECURITY_LEVEL_AUTH_PRIV       SecurityLevel = 3
)

// Enum value maps for SecurityLevel.
var (
	SecurityLevel_name = map[int32]string{
		0: "SECURITY_LEVEL_UNSPECIFIED",
		1: "SECURITY_LEVEL_NO_AUTH_NO_PRIV",
		2: "SECURITY_LEVEL_AUTH_NO_PRIV",
		3: "SECURITY_LEVEL_AUTH_PRIV",
	}
	SecurityLevel_value = map[string]int32{
		"SECURITY_LEVEL_UNSPECIFIED":     0,
		"SECURITY_LEVEL_NO_AUTH_NO_PRIV": 1,
		"SECURITY_LEVEL_AUTH_NO_PRIV":    2,
		"SECURITY_LEVEL_AUTH_PRIV":       3,
	}
)

func (x SecurityLevel) Enum() *SecurityLevel {
	p := new(SecurityLevel)
	*p = x
	return p
}

func (x SecurityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_snmpproxy_proto_enumTypes[2].Descriptor()
}

func (SecurityLevel) Type() protoreflect.EnumType {
	return &file_snmpproxy_proto_enumTypes[2]
}

func (x SecurityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityLevel.Descriptor instead.
func (SecurityLevel) EnumDescriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{2}
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Request/Response correlation. Push messages use id=0.
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Auth
	//	*Envelope_Monitor
	//	*Envelope_Unmonitor
	//	*Envelope_ListTargets
	//	*Envelope_GetTarget
	//	*Envelope_GetHistory
	//	*Envelope_Subscribe
	//	*Envelope_Unsubscribe
	//	*Envelope_GetServerStatus
	//	*Envelope_GetSessionInfo
	//	*Envelope_UpdateTarget
	//	*Envelope_GetConfig
	//	*Envelope_SetConfig
	//	*Envelope_AuthResp
	//	*Envelope_MonitorResp
	//	*Envelope_UnmonitorResp
	//	*Envelope_ListTargetsResp
	//	*Envelope_GetTargetResp
	//	*Envelope_GetHistoryResp
	//	*Envelope_SubscribeResp
	//	*Envelope_UnsubscribeResp
	//	*Envelope_GetServerStatusResp
	//	*Envelope_GetSessionInfoResp
	//	*Envelope_UpdateTargetResp
	//	*Envelope_GetConfigResp
	//	*Envelope_SetConfigResp
	//	*Envelope_Sample
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_snmpproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetAuth() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *Envelope) GetMonitor() *MonitorRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Monitor); ok {
			return x.Monitor
		}
	}
	return nil
}

func (x *Envelope) GetUnmonitor() *UnmonitorRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Unmonitor); ok {
			return x.Unmonitor
		}
	}
	return nil
}

func (x *Envelope) GetListTargets() *ListTargetsRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ListTargets); ok {
			return x.ListTargets
		}
	}
	return nil
}

func (x *Envelope) GetGetTarget() *GetTargetRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetTarget); ok {
			return x.GetTarget
		}
	}
	return nil
}

func (x *Envelope) GetGetHistory() *GetHistoryRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetHistory); ok {
			return x.GetHistory
		}
	}
	return nil
}

func (x *Envelope) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Envelope) GetUnsubscribe() *UnsubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *Envelope) GetGetServerStatus() *GetServerStatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetServerStatus); ok {
			return x.GetServerStatus
		}
	}
	return nil
}

func (x *Envelope) GetGetSessionInfo() *GetSessionInfoRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetSessionInfo); ok {
			return x.GetSessionInfo
		}
	}
	return nil
}

func (x *Envelope) GetUpdateTarget() *UpdateTargetRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UpdateTarget); ok {
			return x.UpdateTarget
		}
	}
	return nil
}

func (x *Envelope) GetGetConfig() *GetConfigRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetConfig); ok {
			return x.GetConfig
		}
	}
	return nil
}

func (x *Envelope) GetSetConfig() *SetConfigRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SetConfig); ok {
			return x.SetConfig
		}
	}
	return nil
}

func (x *Envelope) GetAuthResp() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthResp); ok {
			return x.AuthResp
		}
	}
	return nil
}

func (x *Envelope) GetMonitorResp() *MonitorResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MonitorResp); ok {
			return x.MonitorResp
		}
	}
	return nil
}

func (x *Envelope) GetUnmonitorResp() *UnmonitorResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UnmonitorResp); ok {
			return x.UnmonitorResp
		}
	}
	return nil
}

func (x *Envelope) GetListTargetsResp() *ListTargetsResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ListTargetsResp); ok {
			return x.ListTargetsResp
		}
	}
	return nil
}

func (x *Envelope) GetGetTargetResp() *GetTargetResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetTargetResp); ok {
			return x.GetTargetResp
		}
	}
	return nil
}

func (x *Envelope) GetGetHistoryResp() *GetHistoryResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetHistoryResp); ok {
			return x.GetHistoryResp
		}
	}
	return nil
}

func (x *Envelope) GetSubscribeResp() *SubscribeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SubscribeResp); ok {
			return x.SubscribeResp
		}
	}
	return nil
}

func (x *Envelope) GetUnsubscribeResp() *UnsubscribeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UnsubscribeResp); ok {
			return x.UnsubscribeResp
		}
	}
	return nil
}

func (x *Envelope) GetGetServerStatusResp() *GetServerStatusResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetServerStatusResp); ok {
			return x.GetServerStatusResp
		}
	}
	return nil
}

func (x *Envelope) GetGetSessionInfoResp() *GetSessionInfoResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetSessionInfoResp); ok {
			return x.GetSessionInfoResp
		}
	}
	return nil
}

func (x *Envelope) GetUpdateTargetResp() *UpdateTargetResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UpdateTargetResp); ok {
			return x.UpdateTargetResp
		}
	}
	return nil
}

func (x *Envelope) GetGetConfigResp() *GetConfigResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetConfigResp); ok {
			return x.GetConfigResp
		}
	}
	return nil
}

func (x *Envelope) GetSetConfigResp() *SetConfigResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SetConfigResp); ok {
			return x.SetConfigResp
		}
	}
	return nil
}

func (x *Envelope) GetSample() *Sample {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Sample); ok {
			return x.Sample
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Auth struct {
	// Client → Server
	Auth *AuthRequest `protobuf:"bytes,10,opt,name=auth,proto3,oneof"`
}

type Envelope_Monitor struct {
	Monitor *MonitorRequest `protobuf:"bytes,11,opt,name=monitor,proto3,oneof"`
}

type Envelope_Unmonitor struct {
	Unmonitor *UnmonitorRequest `protobuf:"bytes,12,opt,name=unmonitor,proto3,oneof"`
}

type Envelope_ListTargets struct {
	ListTargets *ListTargetsRequest `protobuf:"bytes,13,opt,name=list_targets,json=listTargets,proto3,oneof"`
}

type Envelope_GetTarget struct {
	GetTarget *GetTargetRequest `protobuf:"bytes,14,opt,name=get_target,json=getTarget,proto3,oneof"`
}

type Envelope_GetHistory struct {
	GetHistory *GetHistoryRequest `protobuf:"bytes,15,opt,name=get_history,json=getHistory,proto3,oneof"`
}

type Envelope_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,16,opt,name=subscribe,proto3,oneof"`
}

type Envelope_Unsubscribe struct {
	Unsubscribe *UnsubscribeRequest `protobuf:"bytes,17,opt,name=unsubscribe,proto3,oneof"`
}

type Envelope_GetServerStatus struct {
	// NEW: Status & Config (Client → Server)
	GetServerStatus *GetServerStatusRequest `protobuf:"bytes,18,opt,name=get_server_status,json=getServerStatus,proto3,oneof"`
}

type Envelope_GetSessionInfo struct {
	GetSessionInfo *GetSessionInfoRequest `protobuf:"bytes,19,opt,name=get_session_info,json=getSessionInfo,proto3,oneof"`
}

type Envelope_UpdateTarget struct {
	UpdateTarget *UpdateTargetRequest `protobuf:"bytes,20,opt,name=update_target,json=updateTarget,proto3,oneof"`
}

type Envelope_GetConfig struct {
	GetConfig *GetConfigRequest `protobuf:"bytes,21,opt,name=get_config,json=getConfig,proto3,oneof"`
}

type Envelope_SetConfig struct {
	SetConfig *SetConfigRequest `protobuf:"bytes,22,opt,name=set_config,json=setConfig,proto3,oneof"`
}

type Envelope_AuthResp struct {
	// Server → Client
	AuthResp *AuthResponse `protobuf:"bytes,50,opt,name=auth_resp,json=authResp,proto3,oneof"`
}

type Envelope_MonitorResp struct {
	MonitorResp *MonitorResponse `protobuf:"bytes,51,opt,name=monitor_resp,json=monitorResp,proto3,oneof"`
}

type Envelope_UnmonitorResp struct {
	UnmonitorResp *UnmonitorResponse `protobuf:"bytes,52,opt,name=unmonitor_resp,json=unmonitorResp,proto3,oneof"`
}

type Envelope_ListTargetsResp struct {
	ListTargetsResp *ListTargetsResponse `protobuf:"bytes,53,opt,name=list_targets_resp,json=listTargetsResp,proto3,oneof"`
}

type Envelope_GetTargetResp struct {
	GetTargetResp *GetTargetResponse `protobuf:"bytes,54,opt,name=get_target_resp,json=getTargetResp,proto3,oneof"`
}

type Envelope_GetHistoryResp struct {
	GetHistoryResp *GetHistoryResponse `protobuf:"bytes,55,opt,name=get_history_resp,json=getHistoryResp,proto3,oneof"`
}

type Envelope_SubscribeResp struct {
	SubscribeResp *SubscribeResponse `protobuf:"bytes,56,opt,name=subscribe_resp,json=subscribeResp,proto3,oneof"`
}

type Envelope_UnsubscribeResp struct {
	UnsubscribeResp *UnsubscribeResponse `protobuf:"bytes,57,opt,name=unsubscribe_resp,json=unsubscribeResp,proto3,oneof"`
}

type Envelope_GetServerStatusResp struct {
	// NEW: Status & Config (Server → Client)
	GetServerStatusResp *GetServerStatusResponse `protobuf:"bytes,58,opt,name=get_server_status_resp,json=getServerStatusResp,proto3,oneof"`
}

type Envelope_GetSessionInfoResp struct {
	GetSessionInfoResp *GetSessionInfoResponse `protobuf:"bytes,59,opt,name=get_session_info_resp,json=getSessionInfoResp,proto3,oneof"`
}

type Envelope_UpdateTargetResp struct {
	UpdateTargetResp *UpdateTargetResponse `protobuf:"bytes,60,opt,name=update_target_resp,json=updateTargetResp,proto3,oneof"`
}

type Envelope_GetConfigResp struct {
	GetConfigResp *GetConfigResponse `protobuf:"bytes,61,opt,name=get_config_resp,json=getConfigResp,proto3,oneof"`
}

type Envelope_SetConfigResp struct {
	SetConfigResp *SetConfigResponse `protobuf:"bytes,62,opt,name=set_config_resp,json=setConfigResp,proto3,oneof"`
}

type Envelope_Sample struct {
	// Server → Client (Push, id=0)
	Sample *Sample `protobuf:"bytes,80,opt,name=sample,proto3,oneof"`
}

type Envelope_Error struct {
	// Server → Client (Error response)
	Error *Error `protobuf:"bytes,99,opt,name=error,proto3,oneof"`
}

func (*Envelope_Auth) isEnvelope_Payload() {}

func (*Envelope_Monitor) isEnvelope_Payload() {}

func (*Envelope_Unmonitor) isEnvelope_Payload() {}

func (*Envelope_ListTargets) isEnvelope_Payload() {}

func (*Envelope_GetTarget) isEnvelope_Payload() {}

func (*Envelope_GetHistory) isEnvelope_Payload() {}

func (*Envelope_Subscribe) isEnvelope_Payload() {}

func (*Envelope_Unsubscribe) isEnvelope_Payload() {}

func (*Envelope_GetServerStatus) isEnvelope_Payload() {}

func (*Envelope_GetSessionInfo) isEnvelope_Payload() {}

func (*Envelope_UpdateTarget) isEnvelope_Payload() {}

func (*Envelope_GetConfig) isEnvelope_Payload() {}

func (*Envelope_SetConfig) isEnvelope_Payload() {}

func (*Envelope_AuthResp) isEnvelope_Payload() {}

func (*Envelope_MonitorResp) isEnvelope_Payload() {}

func (*Envelope_UnmonitorResp) isEnvelope_Payload() {}

func (*Envelope_ListTargetsResp) isEnvelope_Payload() {}

func (*Envelope_GetTargetResp) isEnvelope_Payload() {}

func (*Envelope_GetHistoryResp) isEnvelope_Payload() {}

func (*Envelope_SubscribeResp) isEnvelope_Payload() {}

func (*Envelope_UnsubscribeResp) isEnvelope_Payload() {}

func (*Envelope_GetServerStatusResp) isEnvelope_Payload() {}

func (*Envelope_GetSessionInfoResp) isEnvelope_Payload() {}

func (*Envelope_UpdateTargetResp) isEnvelope_Payload() {}

func (*Envelope_GetConfigResp) isEnvelope_Payload() {}

func (*Envelope_SetConfigResp) isEnvelope_Payload() {}

func (*Envelope_Sample) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_snmpproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Counter       uint64                 `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Valid         bool                   `protobuf:"varint,5,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	PollMs        int32                  `protobuf:"varint,7,opt,name=poll_ms,json=pollMs,proto3" json:"poll_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_snmpproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{2}
}

func (x *Sample) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Sample) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Sample) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *Sample) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Sample) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *Sample) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Sample) GetPollMs() int32 {
	if x != nil {
		return x.PollMs
	}
	return 0
}

type SNMPv2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     string                 `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNMPv2C) Reset() {
	*x = SNMPv2C{}
	mi := &file_snmpproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNMPv2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNMPv2C) ProtoMessage() {}

func (x *SNMPv2C) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNMPv2C.ProtoReflect.Descriptor instead.
func (*SNMPv2C) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{3}
}

func (x *SNMPv2C) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

type SNMPv3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecurityName  string                 `protobuf:"bytes,1,opt,name=security_name,json=securityName,proto3" json:"security_name,omitempty"`
	SecurityLevel SecurityLevel          `protobuf:"varint,2,opt,name=security_level,json=securityLevel,proto3,enum=snmpproxy.v1.SecurityLevel" json:"security_level,omitempty"`
	// Auth (required if security_level >= AUTH_NO_PRIV)
	AuthProtocol AuthProtocol `protobuf:"varint,3,opt,name=auth_protocol,json=authProtocol,proto3,enum=snmpproxy.v1.AuthProtocol" json:"auth_protocol,omitempty"`
	AuthPassword string       `protobuf:"bytes,4,opt,name=auth_password,json=authPassword,proto3" json:"auth_password,omitempty"`
	// Priv (required if security_level == AUTH_PRIV)
	PrivProtocol PrivProtocol `protobuf:"varint,5,opt,name=priv_protocol,json=privProtocol,proto3,enum=snmpproxy.v1.PrivProtocol" json:"priv_protocol,omitempty"`
	PrivPassword string       `protobuf:"bytes,6,opt,name=priv_password,json=privPassword,proto3" json:"priv_password,omitempty"`
	// Optional context
	ContextName   string `protobuf:"bytes,7,opt,name=context_name,json=contextName,proto3" json:"context_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNMPv3) Reset() {
	*x = SNMPv3{}
	mi := &file_snmpproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNMPv3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNMPv3) ProtoMessage() {}

func (x *SNMPv3) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNMPv3.ProtoReflect.Descriptor instead.
func (*SNMPv3) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{4}
}

func (x *SNMPv3) GetSecurityName() string {
	if x != nil {
		return x.SecurityName
	}
	return ""
}

func (x *SNMPv3) GetSecurityLevel() SecurityLevel {
	if x != nil {
		return x.SecurityLevel
	}
	return SecurityLevel_SECURITY_LEVEL_UNSPECIFIED
}

func (x *SNMPv3) GetAuthProtocol() AuthProtocol {
	if x != nil {
		return x.AuthProtocol
	}
	return AuthProtocol_AUTH_PROTOCOL_UNSPECIFIED
}

func (x *SNMPv3) GetAuthPassword() string {
	if x != nil {
		return x.AuthPassword
	}
	return ""
}

func (x *SNMPv3) GetPrivProtocol() PrivProtocol {
	if x != nil {
		return x.PrivProtocol
	}
	return PrivProtocol_PRIV_PROTOCOL_UNSPECIFIED
}

func (x *SNMPv3) GetPrivPassword() string {
	if x != nil {
		return x.PrivPassword
	}
	return ""
}

func (x *SNMPv3) GetContextName() string {
	if x != nil {
		return x.ContextName
	}
	return ""
}

type SNMPConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*SNMPConfig_V2C
	//	*SNMPConfig_V3
	Version       isSNMPConfig_Version `protobuf_oneof:"version"`
	TimeoutMs     uint32               `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Retries       uint32               `protobuf:"varint,4,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNMPConfig) Reset() {
	*x = SNMPConfig{}
	mi := &file_snmpproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNMPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNMPConfig) ProtoMessage() {}

func (x *SNMPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNMPConfig.ProtoReflect.Descriptor instead.
func (*SNMPConfig) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{5}
}

func (x *SNMPConfig) GetVersion() isSNMPConfig_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *SNMPConfig) GetV2C() *SNMPv2C {
	if x != nil {
		if x, ok := x.Version.(*SNMPConfig_V2C); ok {
			return x.V2C
		}
	}
	return nil
}

func (x *SNMPConfig) GetV3() *SNMPv3 {
	if x != nil {
		if x, ok := x.Version.(*SNMPConfig_V3); ok {
			return x.V3
		}
	}
	return nil
}

func (x *SNMPConfig) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *SNMPConfig) GetRetries() uint32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

type isSNMPConfig_Version interface {
	isSNMPConfig_Version()
}

type SNMPConfig_V2C struct {
	V2C *SNMPv2C `protobuf:"bytes,1,opt,name=v2c,proto3,oneof"`
}

type SNMPConfig_V3 struct {
	V3 *SNMPv3 `protobuf:"bytes,2,opt,name=v3,proto3,oneof"`
}

func (*SNMPConfig_V2C) isSNMPConfig_Version() {}

func (*SNMPConfig_V3) isSNMPConfig_Version() {}

type Target struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host       string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port       uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Oid        string                 `protobuf:"bytes,4,opt,name=oid,proto3" json:"oid,omitempty"`
	IntervalMs uint32                 `protobuf:"varint,5,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	BufferSize uint32                 `protobuf:"varint,6,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	// Runtime state
	State           string `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"` // "polling", "unreachable", "error"
	LastPollMs      int64  `protobuf:"varint,11,opt,name=last_poll_ms,json=lastPollMs,proto3" json:"last_poll_ms,omitempty"`
	LastError       string `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Subscribers     int32  `protobuf:"varint,13,opt,name=subscribers,proto3" json:"subscribers,omitempty"`
	SamplesBuffered int32  `protobuf:"varint,14,opt,name=samples_buffered,json=samplesBuffered,proto3" json:"samples_buffered,omitempty"`
	// NEW: Extended statistics
	CreatedAtMs   int64 `protobuf:"varint,20,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	PollsTotal    int64 `protobuf:"varint,21,opt,name=polls_total,json=pollsTotal,proto3" json:"polls_total,omitempty"`
	PollsSuccess  int64 `protobuf:"varint,22,opt,name=polls_success,json=pollsSuccess,proto3" json:"polls_success,omitempty"`
	PollsFailed   int64 `protobuf:"varint,23,opt,name=polls_failed,json=pollsFailed,proto3" json:"polls_failed,omitempty"`
	AvgPollMs     int32 `protobuf:"varint,24,opt,name=avg_poll_ms,json=avgPollMs,proto3" json:"avg_poll_ms,omitempty"`
	MinPollMs     int32 `protobuf:"varint,25,opt,name=min_poll_ms,json=minPollMs,proto3" json:"min_poll_ms,omitempty"`
	MaxPollMs     int32 `protobuf:"varint,26,opt,name=max_poll_ms,json=maxPollMs,proto3" json:"max_poll_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_snmpproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{6}
}

func (x *Target) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Target) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Target) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Target) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *Target) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *Target) GetBufferSize() uint32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *Target) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Target) GetLastPollMs() int64 {
	if x != nil {
		return x.LastPollMs
	}
	return 0
}

func (x *Target) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Target) GetSubscribers() int32 {
	if x != nil {
		return x.Subscribers
	}
	return 0
}

func (x *Target) GetSamplesBuffered() int32 {
	if x != nil {
		return x.SamplesBuffered
	}
	return 0
}

func (x *Target) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *Target) GetPollsTotal() int64 {
	if x != nil {
		return x.PollsTotal
	}
	return 0
}

func (x *Target) GetPollsSuccess() int64 {
	if x != nil {
		return x.PollsSuccess
	}
	return 0
}

func (x *Target) GetPollsFailed() int64 {
	if x != nil {
		return x.PollsFailed
	}
	return 0
}

func (x *Target) GetAvgPollMs() int32 {
	if x != nil {
		return x.AvgPollMs
	}
	return 0
}

func (x *Target) GetMinPollMs() int32 {
	if x != nil {
		return x.MinPollMs
	}
	return 0
}

func (x *Target) GetMaxPollMs() int32 {
	if x != nil {
		return x.MaxPollMs
	}
	return 0
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_snmpproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{7}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_snmpproxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{8}
}

func (x *AuthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // Default: 161
	Oid           string                 `protobuf:"bytes,3,opt,name=oid,proto3" json:"oid,omitempty"`
	IntervalMs    uint32                 `protobuf:"varint,4,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // Default: 1000
	BufferSize    uint32                 `protobuf:"varint,5,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"` // Default: 3600
	Snmp          *SNMPConfig            `protobuf:"bytes,6,opt,name=snmp,proto3" json:"snmp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorRequest) Reset() {
	*x = MonitorRequest{}
	mi := &file_snmpproxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorRequest) ProtoMessage() {}

func (x *MonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorRequest.ProtoReflect.Descriptor instead.
func (*MonitorRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{9}
}

func (x *MonitorRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MonitorRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MonitorRequest) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *MonitorRequest) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *MonitorRequest) GetBufferSize() uint32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *MonitorRequest) GetSnmp() *SNMPConfig {
	if x != nil {
		return x.Snmp
	}
	return nil
}

type MonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"` // true if new, false if joined existing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorResponse) Reset() {
	*x = MonitorResponse{}
	mi := &file_snmpproxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorResponse) ProtoMessage() {}

func (x *MonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorResponse.ProtoReflect.Descriptor instead.
func (*MonitorResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{10}
}

func (x *MonitorResponse) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *MonitorResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type UnmonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmonitorRequest) Reset() {
	*x = UnmonitorRequest{}
	mi := &file_snmpproxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmonitorRequest) ProtoMessage() {}

func (x *UnmonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmonitorRequest.ProtoReflect.Descriptor instead.
func (*UnmonitorRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{11}
}

func (x *UnmonitorRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type UnmonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmonitorResponse) Reset() {
	*x = UnmonitorResponse{}
	mi := &file_snmpproxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmonitorResponse) ProtoMessage() {}

func (x *UnmonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmonitorResponse.ProtoReflect.Descriptor instead.
func (*UnmonitorResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{12}
}

func (x *UnmonitorResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListTargetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterHost    string                 `protobuf:"bytes,1,opt,name=filter_host,json=filterHost,proto3" json:"filter_host,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTargetsRequest) Reset() {
	*x = ListTargetsRequest{}
	mi := &file_snmpproxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetsRequest) ProtoMessage() {}

func (x *ListTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTargetsRequest.ProtoReflect.Descriptor instead.
func (*ListTargetsRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{13}
}

func (x *ListTargetsRequest) GetFilterHost() string {
	if x != nil {
		return x.FilterHost
	}
	return ""
}

type ListTargetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*Target              `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTargetsResponse) Reset() {
	*x = ListTargetsResponse{}
	mi := &file_snmpproxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetsResponse) ProtoMessage() {}

func (x *ListTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTargetsResponse.ProtoReflect.Descriptor instead.
func (*ListTargetsResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{14}
}

func (x *ListTargetsResponse) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

type GetTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetRequest) Reset() {
	*x = GetTargetRequest{}
	mi := &file_snmpproxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetRequest) ProtoMessage() {}

func (x *GetTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetRequest.ProtoReflect.Descriptor instead.
func (*GetTargetRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{15}
}

func (x *GetTargetRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type GetTargetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Target                `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetResponse) Reset() {
	*x = GetTargetResponse{}
	mi := &file_snmpproxy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetResponse) ProtoMessage() {}

func (x *GetTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetResponse.ProtoReflect.Descriptor instead.
func (*GetTargetResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{16}
}

func (x *GetTargetResponse) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIds     []string               `protobuf:"bytes,1,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	LastN         uint32                 `protobuf:"varint,2,opt,name=last_n,json=lastN,proto3" json:"last_n,omitempty"` // Number of samples (default: 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_snmpproxy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{17}
}

func (x *GetHistoryRequest) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *GetHistoryRequest) GetLastN() uint32 {
	if x != nil {
		return x.LastN
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*TargetHistory       `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_snmpproxy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{18}
}

func (x *GetHistoryResponse) GetHistory() []*TargetHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type TargetHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Samples       []*Sample              `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetHistory) Reset() {
	*x = TargetHistory{}
	mi := &file_snmpproxy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetHistory) ProtoMessage() {}

func (x *TargetHistory) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetHistory.ProtoReflect.Descriptor instead.
func (*TargetHistory) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{19}
}

func (x *TargetHistory) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *TargetHistory) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIds     []string               `protobuf:"bytes,1,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_snmpproxy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{20}
}

func (x *SubscribeRequest) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Subscribed    []string               `protobuf:"bytes,2,rep,name=subscribed,proto3" json:"subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_snmpproxy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{21}
}

func (x *SubscribeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubscribeResponse) GetSubscribed() []string {
	if x != nil {
		return x.Subscribed
	}
	return nil
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIds     []string               `protobuf:"bytes,1,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"` // Empty = unsubscribe all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_snmpproxy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{22}
}

func (x *UnsubscribeRequest) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_snmpproxy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{23}
}

func (x *UnsubscribeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatusRequest) Reset() {
	*x = GetServerStatusRequest{}
	mi := &file_snmpproxy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusRequest) ProtoMessage() {}

func (x *GetServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{24}
}

type GetServerStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// General
	Version     string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeMs    int64  `protobuf:"varint,2,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	StartedAtMs int64  `protobuf:"varint,3,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	// Sessions
	SessionsActive int32 `protobuf:"varint,10,opt,name=sessions_active,json=sessionsActive,proto3" json:"sessions_active,omitempty"`
	SessionsLost   int32 `protobuf:"varint,11,opt,name=sessions_lost,json=sessionsLost,proto3" json:"sessions_lost,omitempty"`
	// Targets
	TargetsTotal       int32 `protobuf:"varint,20,opt,name=targets_total,json=targetsTotal,proto3" json:"targets_total,omitempty"`
	TargetsPolling     int32 `protobuf:"varint,21,opt,name=targets_polling,json=targetsPolling,proto3" json:"targets_polling,omitempty"`
	TargetsUnreachable int32 `protobuf:"varint,22,opt,name=targets_unreachable,json=targetsUnreachable,proto3" json:"targets_unreachable,omitempty"`
	// Poller
	PollerWorkers       int32 `protobuf:"varint,30,opt,name=poller_workers,json=pollerWorkers,proto3" json:"poller_workers,omitempty"`
	PollerQueueUsed     int32 `protobuf:"varint,31,opt,name=poller_queue_used,json=pollerQueueUsed,proto3" json:"poller_queue_used,omitempty"`
	PollerQueueCapacity int32 `protobuf:"varint,32,opt,name=poller_queue_capacity,json=pollerQueueCapacity,proto3" json:"poller_queue_capacity,omitempty"`
	PollerHeapSize      int32 `protobuf:"varint,33,opt,name=poller_heap_size,json=pollerHeapSize,proto3" json:"poller_heap_size,omitempty"`
	// Statistics (since start)
	PollsTotal    int64 `protobuf:"varint,40,opt,name=polls_total,json=pollsTotal,proto3" json:"polls_total,omitempty"`
	PollsSuccess  int64 `protobuf:"varint,41,opt,name=polls_success,json=pollsSuccess,proto3" json:"polls_success,omitempty"`
	PollsFailed   int64 `protobuf:"varint,42,opt,name=polls_failed,json=pollsFailed,proto3" json:"polls_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatusResponse) Reset() {
	*x = GetServerStatusResponse{}
	mi := &file_snmpproxy_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusResponse) ProtoMessage() {}

func (x *GetServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{25}
}

func (x *GetServerStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetServerStatusResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *GetServerStatusResponse) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *GetServerStatusResponse) GetSessionsActive() int32 {
	if x != nil {
		return x.SessionsActive
	}
	return 0
}

func (x *GetServerStatusResponse) GetSessionsLost() int32 {
	if x != nil {
		return x.SessionsLost
	}
	return 0
}

func (x *GetServerStatusResponse) GetTargetsTotal() int32 {
	if x != nil {
		return x.TargetsTotal
	}
	return 0
}

func (x *GetServerStatusResponse) GetTargetsPolling() int32 {
	if x != nil {
		return x.TargetsPolling
	}
	return 0
}

func (x *GetServerStatusResponse) GetTargetsUnreachable() int32 {
	if x != nil {
		return x.TargetsUnreachable
	}
	return 0
}

func (x *GetServerStatusResponse) GetPollerWorkers() int32 {
	if x != nil {
		return x.PollerWorkers
	}
	return 0
}

func (x *GetServerStatusResponse) GetPollerQueueUsed() int32 {
	if x != nil {
		return x.PollerQueueUsed
	}
	return 0
}

func (x *GetServerStatusResponse) GetPollerQueueCapacity() int32 {
	if x != nil {
		return x.PollerQueueCapacity
	}
	return 0
}

func (x *GetServerStatusResponse) GetPollerHeapSize() int32 {
	if x != nil {
		return x.PollerHeapSize
	}
	return 0
}

func (x *GetServerStatusResponse) GetPollsTotal() int64 {
	if x != nil {
		return x.PollsTotal
	}
	return 0
}

func (x *GetServerStatusResponse) GetPollsSuccess() int64 {
	if x != nil {
		return x.PollsSuccess
	}
	return 0
}

func (x *GetServerStatusResponse) GetPollsFailed() int64 {
	if x != nil {
		return x.PollsFailed
	}
	return 0
}

type GetSessionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionInfoRequest) Reset() {
	*x = GetSessionInfoRequest{}
	mi := &file_snmpproxy_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionInfoRequest) ProtoMessage() {}

func (x *GetSessionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSessionInfoRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{26}
}

type GetSessionInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TokenId           string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	CreatedAtMs       int64                  `protobuf:"varint,3,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	ConnectedAtMs     int64                  `protobuf:"varint,4,opt,name=connected_at_ms,json=connectedAtMs,proto3" json:"connected_at_ms,omitempty"`
	OwnedTargets      []string               `protobuf:"bytes,10,rep,name=owned_targets,json=ownedTargets,proto3" json:"owned_targets,omitempty"`
	SubscribedTargets []string               `protobuf:"bytes,11,rep,name=subscribed_targets,json=subscribedTargets,proto3" json:"subscribed_targets,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSessionInfoResponse) Reset() {
	*x = GetSessionInfoResponse{}
	mi := &file_snmpproxy_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionInfoResponse) ProtoMessage() {}

func (x *GetSessionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSessionInfoResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{27}
}

func (x *GetSessionInfoResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionInfoResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *GetSessionInfoResponse) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *GetSessionInfoResponse) GetConnectedAtMs() int64 {
	if x != nil {
		return x.ConnectedAtMs
	}
	return 0
}

func (x *GetSessionInfoResponse) GetOwnedTargets() []string {
	if x != nil {
		return x.OwnedTargets
	}
	return nil
}

func (x *GetSessionInfoResponse) GetSubscribedTargets() []string {
	if x != nil {
		return x.SubscribedTargets
	}
	return nil
}

type UpdateTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	IntervalMs    uint32                 `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // 0 = don't change
	TimeoutMs     uint32                 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`    // 0 = don't change
	Retries       uint32                 `protobuf:"varint,4,opt,name=retries,proto3" json:"retries,omitempty"`                         // 0 = don't change
	BufferSize    uint32                 `protobuf:"varint,5,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"` // 0 = don't change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTargetRequest) Reset() {
	*x = UpdateTargetRequest{}
	mi := &file_snmpproxy_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTargetRequest) ProtoMessage() {}

func (x *UpdateTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTargetRequest.ProtoReflect.Descriptor instead.
func (*UpdateTargetRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateTargetRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *UpdateTargetRequest) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *UpdateTargetRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *UpdateTargetRequest) GetRetries() uint32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *UpdateTargetRequest) GetBufferSize() uint32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

type UpdateTargetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Target        *Target                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTargetResponse) Reset() {
	*x = UpdateTargetResponse{}
	mi := &file_snmpproxy_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTargetResponse) ProtoMessage() {}

func (x *UpdateTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTargetResponse.ProtoReflect.Descriptor instead.
func (*UpdateTargetResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateTargetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpdateTargetResponse) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *UpdateTargetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_snmpproxy_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{30}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *RuntimeConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_snmpproxy_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{31}
}

func (x *GetConfigResponse) GetConfig() *RuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SetConfigRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DefaultTimeoutMs  uint32                 `protobuf:"varint,1,opt,name=default_timeout_ms,json=defaultTimeoutMs,proto3" json:"default_timeout_ms,omitempty"`    // 0 = don't change
	DefaultRetries    uint32                 `protobuf:"varint,2,opt,name=default_retries,json=defaultRetries,proto3" json:"default_retries,omitempty"`            // 0 = don't change
	DefaultBufferSize uint32                 `protobuf:"varint,3,opt,name=default_buffer_size,json=defaultBufferSize,proto3" json:"default_buffer_size,omitempty"` // 0 = don't change
	MinIntervalMs     uint32                 `protobuf:"varint,4,opt,name=min_interval_ms,json=minIntervalMs,proto3" json:"min_interval_ms,omitempty"`             // 0 = don't change
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_snmpproxy_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{32}
}

func (x *SetConfigRequest) GetDefaultTimeoutMs() uint32 {
	if x != nil {
		return x.DefaultTimeoutMs
	}
	return 0
}

func (x *SetConfigRequest) GetDefaultRetries() uint32 {
	if x != nil {
		return x.DefaultRetries
	}
	return 0
}

func (x *SetConfigRequest) GetDefaultBufferSize() uint32 {
	if x != nil {
		return x.DefaultBufferSize
	}
	return 0
}

func (x *SetConfigRequest) GetMinIntervalMs() uint32 {
	if x != nil {
		return x.MinIntervalMs
	}
	return 0
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Config        *RuntimeConfig         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_snmpproxy_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{33}
}

func (x *SetConfigResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetConfigResponse) GetConfig() *RuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RuntimeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Changeable at runtime
	DefaultTimeoutMs  uint32 `protobuf:"varint,1,opt,name=default_timeout_ms,json=defaultTimeoutMs,proto3" json:"default_timeout_ms,omitempty"`
	DefaultRetries    uint32 `protobuf:"varint,2,opt,name=default_retries,json=defaultRetries,proto3" json:"default_retries,omitempty"`
	DefaultBufferSize uint32 `protobuf:"varint,3,opt,name=default_buffer_size,json=defaultBufferSize,proto3" json:"default_buffer_size,omitempty"`
	MinIntervalMs     uint32 `protobuf:"varint,4,opt,name=min_interval_ms,json=minIntervalMs,proto3" json:"min_interval_ms,omitempty"`
	// Read-only (set at startup)
	PollerWorkers      int32  `protobuf:"varint,10,opt,name=poller_workers,json=pollerWorkers,proto3" json:"poller_workers,omitempty"`
	PollerQueueSize    int32  `protobuf:"varint,11,opt,name=poller_queue_size,json=pollerQueueSize,proto3" json:"poller_queue_size,omitempty"`
	ReconnectWindowSec uint32 `protobuf:"varint,12,opt,name=reconnect_window_sec,json=reconnectWindowSec,proto3" json:"reconnect_window_sec,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RuntimeConfig) Reset() {
	*x = RuntimeConfig{}
	mi := &file_snmpproxy_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeConfig) ProtoMessage() {}

func (x *RuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snmpproxy_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeConfig.ProtoReflect.Descriptor instead.
func (*RuntimeConfig) Descriptor() ([]byte, []int) {
	return file_snmpproxy_proto_rawDescGZIP(), []int{34}
}

func (x *RuntimeConfig) GetDefaultTimeoutMs() uint32 {
	if x != nil {
		return x.DefaultTimeoutMs
	}
	return 0
}

func (x *RuntimeConfig) GetDefaultRetries() uint32 {
	if x != nil {
		return x.DefaultRetries
	}
	return 0
}

func (x *RuntimeConfig) GetDefaultBufferSize() uint32 {
	if x != nil {
		return x.DefaultBufferSize
	}
	return 0
}

func (x *RuntimeConfig) GetMinIntervalMs() uint32 {
	if x != nil {
		return x.MinIntervalMs
	}
	return 0
}

func (x *RuntimeConfig) GetPollerWorkers() int32 {
	if x != nil {
		return x.PollerWorkers
	}
	return 0
}

func (x *RuntimeConfig) GetPollerQueueSize() int32 {
	if x != nil {
		return x.PollerQueueSize
	}
	return 0
}

func (x *RuntimeConfig) GetReconnectWindowSec() uint32 {
	if x != nil {
		return x.ReconnectWindowSec
	}
	return 0
}

var File_snmpproxy_proto protoreflect.FileDescriptor

const file_snmpproxy_proto_rawDesc = "" +
	"\n" +
	"\x0fsnmpproxy.proto\x12\fsnmpproxy.v1\"\xe0\x0f\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12/\n" +
	"\x04auth\x18\n" +
	" \x01(\v2\x19.snmpproxy.v1.AuthRequestH\x00R\x04auth\x128\n" +
	"\amonitor\x18\v \x01(\v2\x1c.snmpproxy.v1.MonitorRequestH\x00R\amonitor\x12>\n" +
	"\tunmonitor\x18\f \x01(\v2\x1e.snmpproxy.v1.UnmonitorRequestH\x00R\tunmonitor\x12E\n" +
	"\flist_targets\x18\r \x01(\v2 .snmpproxy.v1.ListTargetsRequestH\x00R\vlistTargets\x12?\n" +
	"\n" +
	"get_target\x18\x0e \x01(\v2\x1e.snmpproxy.v1.GetTargetRequestH\x00R\tgetTarget\x12B\n" +
	"\vget_history\x18\x0f \x01(\v2\x1f.snmpproxy.v1.GetHistoryRequestH\x00R\n" +
	"getHistory\x12>\n" +
	"\tsubscribe\x18\x10 \x01(\v2\x1e.snmpproxy.v1.SubscribeRequestH\x00R\tsubscribe\x12D\n" +
	"\vunsubscribe\x18\x11 \x01(\v2 .snmpproxy.v1.UnsubscribeRequestH\x00R\vunsubscribe\x12R\n" +
	"\x11get_server_status\x18\x12 \x01(\v2$.snmpproxy.v1.GetServerStatusRequestH\x00R\x0fgetServerStatus\x12O\n" +
	"\x10get_session_info\x18\x13 \x01(\v2#.snmpproxy.v1.GetSessionInfoRequestH\x00R\x0egetSessionInfo\x12H\n" +
	"\rupdate_target\x18\x14 \x01(\v2!.snmpproxy.v1.UpdateTargetRequestH\x00R\fupdateTarget\x12?\n" +
	"\n" +
	"get_config\x18\x15 \x01(\v2\x1e.snmpproxy.v1.GetConfigRequestH\x00R\tgetConfig\x12?\n" +
	"\n" +
	"set_config\x18\x16 \x01(\v2\x1e.snmpproxy.v1.SetConfigRequestH\x00R\tsetConfig\x129\n" +
	"\tauth_resp\x182 \x01(\v2\x1a.snmpproxy.v1.AuthResponseH\x00R\bauthResp\x12B\n" +
	"\fmonitor_resp\x183 \x01(\v2\x1d.snmpproxy.v1.MonitorResponseH\x00R\vmonitorResp\x12H\n" +
	"\x0eunmonitor_resp\x184 \x01(\v2\x1f.snmpproxy.v1.UnmonitorResponseH\x00R\runmonitorResp\x12O\n" +
	"\x11list_targets_resp\x185 \x01(\v2!.snmpproxy.v1.ListTargetsResponseH\x00R\x0flistTargetsResp\x12I\n" +
	"\x0fget_target_resp\x186 \x01(\v2\x1f.snmpproxy.v1.GetTargetResponseH\x00R\rgetTargetResp\x12L\n" +
	"\x10get_history_resp\x187 \x01(\v2 .snmpproxy.v1.GetHistoryResponseH\x00R\x0egetHistoryResp\x12H\n" +
	"\x0esubscribe_resp\x188 \x01(\v2\x1f.snmpproxy.v1.SubscribeResponseH\x00R\rsubscribeResp\x12N\n" +
	"\x10unsubscribe_resp\x189 \x01(\v2!.snmpproxy.v1.UnsubscribeResponseH\x00R\x0funsubscribeResp\x12\\\n" +
	"\x16get_server_status_resp\x18: \x01(\v2%.snmpproxy.v1.GetServerStatusResponseH\x00R\x13getServerStatusResp\x12Y\n" +
	"\x15get_session_info_resp\x18; \x01(\v2$.snmpproxy.v1.GetSessionInfoResponseH\x00R\x12getSessionInfoResp\x12R\n" +
	"\x12update_target_resp\x18< \x01(\v2\".snmpproxy.v1.UpdateTargetResponseH\x00R\x10updateTargetResp\x12I\n" +
	"\x0fget_config_resp\x18= \x01(\v2\x1f.snmpproxy.v1.GetConfigResponseH\x00R\rgetConfigResp\x12I\n" +
	"\x0fset_config_resp\x18> \x01(\v2\x1f.snmpproxy.v1.SetConfigResponseH\x00R\rsetConfigResp\x12.\n" +
	"\x06sample\x18P \x01(\v2\x14.snmpproxy.v1.SampleH\x00R\x06sample\x12+\n" +
	"\x05error\x18c \x01(\v2\x13.snmpproxy.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x01\n" +
	"\x06Sample\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x18\n" +
	"\acounter\x18\x03 \x01(\x04R\acounter\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05valid\x18\x05 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x17\n" +
	"\apoll_ms\x18\a \x01(\x05R\x06pollMs\"'\n" +
	"\aSNMPv2c\x12\x1c\n" +
	"\tcommunity\x18\x01 \x01(\tR\tcommunity\"\xe0\x02\n" +
	"\x06SNMPv3\x12#\n" +
	"\rsecurity_name\x18\x01 \x01(\tR\fsecurityName\x12B\n" +
	"\x0esecurity_level\x18\x02 \x01(\x0e2\x1b.snmpproxy.v1.SecurityLevelR\rsecurityLevel\x12?\n" +
	"\rauth_protocol\x18\x03 \x01(\x0e2\x1a.snmpproxy.v1.AuthProtocolR\fauthProtocol\x12#\n" +
	"\rauth_password\x18\x04 \x01(\tR\fauthPassword\x12?\n" +
	"\rpriv_protocol\x18\x05 \x01(\x0e2\x1a.snmpproxy.v1.PrivProtocolR\fprivProtocol\x12#\n" +
	"\rpriv_password\x18\x06 \x01(\tR\fprivPassword\x12!\n" +
	"\fcontext_name\x18\a \x01(\tR\vcontextName\"\xa3\x01\n" +
	"\n" +
	"SNMPConfig\x12)\n" +
	"\x03v2c\x18\x01 \x01(\v2\x15.snmpproxy.v1.SNMPv2cH\x00R\x03v2c\x12&\n" +
	"\x02v3\x18\x02 \x01(\v2\x14.snmpproxy.v1.SNMPv3H\x00R\x02v3\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\x12\x18\n" +
	"\aretries\x18\x04 \x01(\rR\aretriesB\t\n" +
	"\aversion\"\xa5\x04\n" +
	"\x06Target\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x10\n" +
	"\x03oid\x18\x04 \x01(\tR\x03oid\x12\x1f\n" +
	"\vinterval_ms\x18\x05 \x01(\rR\n" +
	"intervalMs\x12\x1f\n" +
	"\vbuffer_size\x18\x06 \x01(\rR\n" +
	"bufferSize\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12 \n" +
	"\flast_poll_ms\x18\v \x01(\x03R\n" +
	"lastPollMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\x12 \n" +
	"\vsubscribers\x18\r \x01(\x05R\vsubscribers\x12)\n" +
	"\x10samples_buffered\x18\x0e \x01(\x05R\x0fsamplesBuffered\x12\"\n" +
	"\rcreated_at_ms\x18\x14 \x01(\x03R\vcreatedAtMs\x12\x1f\n" +
	"\vpolls_total\x18\x15 \x01(\x03R\n" +
	"pollsTotal\x12#\n" +
	"\rpolls_success\x18\x16 \x01(\x03R\fpollsSuccess\x12!\n" +
	"\fpolls_failed\x18\x17 \x01(\x03R\vpollsFailed\x12\x1e\n" +
	"\vavg_poll_ms\x18\x18 \x01(\x05R\tavgPollMs\x12\x1e\n" +
	"\vmin_poll_ms\x18\x19 \x01(\x05R\tminPollMs\x12\x1e\n" +
	"\vmax_poll_ms\x18\x1a \x01(\x05R\tmaxPollMs\"#\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"W\n" +
	"\fAuthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xba\x01\n" +
	"\x0eMonitorRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x10\n" +
	"\x03oid\x18\x03 \x01(\tR\x03oid\x12\x1f\n" +
	"\vinterval_ms\x18\x04 \x01(\rR\n" +
	"intervalMs\x12\x1f\n" +
	"\vbuffer_size\x18\x05 \x01(\rR\n" +
	"bufferSize\x12,\n" +
	"\x04snmp\x18\x06 \x01(\v2\x18.snmpproxy.v1.SNMPConfigR\x04snmp\"H\n" +
	"\x0fMonitorResponse\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"/\n" +
	"\x10UnmonitorRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"#\n" +
	"\x11UnmonitorResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"5\n" +
	"\x12ListTargetsRequest\x12\x1f\n" +
	"\vfilter_host\x18\x01 \x01(\tR\n" +
	"filterHost\"E\n" +
	"\x13ListTargetsResponse\x12.\n" +
	"\atargets\x18\x01 \x03(\v2\x14.snmpproxy.v1.TargetR\atargets\"/\n" +
	"\x10GetTargetRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"A\n" +
	"\x11GetTargetResponse\x12,\n" +
	"\x06target\x18\x01 \x01(\v2\x14.snmpproxy.v1.TargetR\x06target\"I\n" +
	"\x11GetHistoryRequest\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x01 \x03(\tR\ttargetIds\x12\x15\n" +
	"\x06last_n\x18\x02 \x01(\rR\x05lastN\"K\n" +
	"\x12GetHistoryResponse\x125\n" +
	"\ahistory\x18\x01 \x03(\v2\x1b.snmpproxy.v1.TargetHistoryR\ahistory\"\\\n" +
	"\rTargetHistory\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12.\n" +
	"\asamples\x18\x02 \x03(\v2\x14.snmpproxy.v1.SampleR\asamples\"1\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x01 \x03(\tR\ttargetIds\"C\n" +
	"\x11SubscribeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1e\n" +
	"\n" +
	"subscribed\x18\x02 \x03(\tR\n" +
	"subscribed\"3\n" +
	"\x12UnsubscribeRequest\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x01 \x03(\tR\ttargetIds\"%\n" +
	"\x13UnsubscribeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x18\n" +
	"\x16GetServerStatusRequest\"\xdb\x04\n" +
	"\x17GetServerStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1b\n" +
	"\tuptime_ms\x18\x02 \x01(\x03R\buptimeMs\x12\"\n" +
	"\rstarted_at_ms\x18\x03 \x01(\x03R\vstartedAtMs\x12'\n" +
	"\x0fsessions_active\x18\n" +
	" \x01(\x05R\x0esessionsActive\x12#\n" +
	"\rsessions_lost\x18\v \x01(\x05R\fsessionsLost\x12#\n" +
	"\rtargets_total\x18\x14 \x01(\x05R\ftargetsTotal\x12'\n" +
	"\x0ftargets_polling\x18\x15 \x01(\x05R\x0etargetsPolling\x12/\n" +
	"\x13targets_unreachable\x18\x16 \x01(\x05R\x12targetsUnreachable\x12%\n" +
	"\x0epoller_workers\x18\x1e \x01(\x05R\rpollerWorkers\x12*\n" +
	"\x11poller_queue_used\x18\x1f \x01(\x05R\x0fpollerQueueUsed\x122\n" +
	"\x15poller_queue_capacity\x18  \x01(\x05R\x13pollerQueueCapacity\x12(\n" +
	"\x10poller_heap_size\x18! \x01(\x05R\x0epollerHeapSize\x12\x1f\n" +
	"\vpolls_total\x18( \x01(\x03R\n" +
	"pollsTotal\x12#\n" +
	"\rpolls_success\x18) \x01(\x03R\fpollsSuccess\x12!\n" +
	"\fpolls_failed\x18* \x01(\x03R\vpollsFailed\"\x17\n" +
	"\x15GetSessionInfoRequest\"\xf2\x01\n" +
	"\x16GetSessionInfoResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12\"\n" +
	"\rcreated_at_ms\x18\x03 \x01(\x03R\vcreatedAtMs\x12&\n" +
	"\x0fconnected_at_ms\x18\x04 \x01(\x03R\rconnectedAtMs\x12#\n" +
	"\rowned_targets\x18\n" +
	" \x03(\tR\fownedTargets\x12-\n" +
	"\x12subscribed_targets\x18\v \x03(\tR\x11subscribedTargets\"\xad\x01\n" +
	"\x13UpdateTargetRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\rR\n" +
	"intervalMs\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\x12\x18\n" +
	"\aretries\x18\x04 \x01(\rR\aretries\x12\x1f\n" +
	"\vbuffer_size\x18\x05 \x01(\rR\n" +
	"bufferSize\"n\n" +
	"\x14UpdateTargetResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12,\n" +
	"\x06target\x18\x02 \x01(\v2\x14.snmpproxy.v1.TargetR\x06target\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x12\n" +
	"\x10GetConfigRequest\"H\n" +
	"\x11GetConfigResponse\x123\n" +
	"\x06config\x18\x01 \x01(\v2\x1b.snmpproxy.v1.RuntimeConfigR\x06config\"\xc1\x01\n" +
	"\x10SetConfigRequest\x12,\n" +
	"\x12default_timeout_ms\x18\x01 \x01(\rR\x10defaultTimeoutMs\x12'\n" +
	"\x0fdefault_retries\x18\x02 \x01(\rR\x0edefaultRetries\x12.\n" +
	"\x13default_buffer_size\x18\x03 \x01(\rR\x11defaultBufferSize\x12&\n" +
	"\x0fmin_interval_ms\x18\x04 \x01(\rR\rminIntervalMs\"r\n" +
	"\x11SetConfigResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x123\n" +
	"\x06config\x18\x02 \x01(\v2\x1b.snmpproxy.v1.RuntimeConfigR\x06config\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc3\x02\n" +
	"\rRuntimeConfig\x12,\n" +
	"\x12default_timeout_ms\x18\x01 \x01(\rR\x10defaultTimeoutMs\x12'\n" +
	"\x0fdefault_retries\x18\x02 \x01(\rR\x0edefaultRetries\x12.\n" +
	"\x13default_buffer_size\x18\x03 \x01(\rR\x11defaultBufferSize\x12&\n" +
	"\x0fmin_interval_ms\x18\x04 \x01(\rR\rminIntervalMs\x12%\n" +
	"\x0epoller_workers\x18\n" +
	" \x01(\x05R\rpollerWorkers\x12*\n" +
	"\x11poller_queue_size\x18\v \x01(\x05R\x0fpollerQueueSize\x120\n" +
	"\x14reconnect_window_sec\x18\f \x01(\rR\x12reconnectWindowSec*\xc3\x01\n" +
	"\fAuthProtocol\x12\x1d\n" +
	"\x19AUTH_PROTOCOL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AUTH_PROTOCOL_MD5\x10\x01\x12\x15\n" +
	"\x11AUTH_PROTOCOL_SHA\x10\x02\x12\x18\n" +
	"\x14AUTH_PROTOCOL_SHA224\x10\x03\x12\x18\n" +
	"\x14AUTH_PROTOCOL_SHA256\x10\x04\x12\x18\n" +
	"\x14AUTH_PROTOCOL_SHA384\x10\x05\x12\x18\n" +
	"\x14AUTH_PROTOCOL_SHA512\x10\x06*\x8f\x01\n" +
	"\fPrivProtocol\x12\x1d\n" +
	"\x19PRIV_PROTOCOL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PRIV_PROTOCOL_DES\x10\x01\x12\x15\n" +
	"\x11PRIV_PROTOCOL_AES\x10\x02\x12\x18\n" +
	"\x14PRIV_PROTOCOL_AES192\x10\x03\x12\x18\n" +
	"\x14PRIV_PROTOCOL_AES256\x10\x04*\x92\x01\n" +
	"\rSecurityLevel\x12\x1e\n" +
	"\x1aSECURITY_LEVEL_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSECURITY_LEVEL_NO_AUTH_NO_PRIV\x10\x01\x12\x1f\n" +
	"\x1bSECURITY_LEVEL_AUTH_NO_PRIV\x10\x02\x12\x1c\n" +
	"\x18SECURITY_LEVEL_AUTH_PRIV\x10\x03B,Z*github.com/xtxerr/snmpproxy/internal/protob\x06proto3"

var (
	file_snmpproxy_proto_rawDescOnce sync.Once
	file_snmpproxy_proto_rawDescData []byte
)

func file_snmpproxy_proto_rawDescGZIP() []byte {
	file_snmpproxy_proto_rawDescOnce.Do(func() {
		file_snmpproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snmpproxy_proto_rawDesc), len(file_snmpproxy_proto_rawDesc)))
	})
	return file_snmpproxy_proto_rawDescData
}

var file_snmpproxy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_snmpproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_snmpproxy_proto_goTypes = []any{
	(AuthProtocol)(0),               // 0: snmpproxy.v1.AuthProtocol
	(PrivProtocol)(0),               // 1: snmpproxy.v1.PrivProtocol
	(SecurityLevel)(0),              // 2: snmpproxy.v1.SecurityLevel
	(*Envelope)(nil),                // 3: snmpproxy.v1.Envelope
	(*Error)(nil),                   // 4: snmpproxy.v1.Error
	(*Sample)(nil),                  // 5: snmpproxy.v1.Sample
	(*SNMPv2C)(nil),                 // 6: snmpproxy.v1.SNMPv2c
	(*SNMPv3)(nil),                  // 7: snmpproxy.v1.SNMPv3
	(*SNMPConfig)(nil),              // 8: snmpproxy.v1.SNMPConfig
	(*Target)(nil),                  // 9: snmpproxy.v1.Target
	(*AuthRequest)(nil),             // 10: snmpproxy.v1.AuthRequest
	(*AuthResponse)(nil),            // 11: snmpproxy.v1.AuthResponse
	(*MonitorRequest)(nil),          // 12: snmpproxy.v1.MonitorRequest
	(*MonitorResponse)(nil),         // 13: snmpproxy.v1.MonitorResponse
	(*UnmonitorRequest)(nil),        // 14: snmpproxy.v1.UnmonitorRequest
	(*UnmonitorResponse)(nil),       // 15: snmpproxy.v1.UnmonitorResponse
	(*ListTargetsRequest)(nil),      // 16: snmpproxy.v1.ListTargetsRequest
	(*ListTargetsResponse)(nil),     // 17: snmpproxy.v1.ListTargetsResponse
	(*GetTargetRequest)(nil),        // 18: snmpproxy.v1.GetTargetRequest
	(*GetTargetResponse)(nil),       // 19: snmpproxy.v1.GetTargetResponse
	(*GetHistoryRequest)(nil),       // 20: snmpproxy.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),      // 21: snmpproxy.v1.GetHistoryResponse
	(*TargetHistory)(nil),           // 22: snmpproxy.v1.TargetHistory
	(*SubscribeRequest)(nil),        // 23: snmpproxy.v1.SubscribeRequest
	(*SubscribeResponse)(nil),       // 24: snmpproxy.v1.SubscribeResponse
	(*UnsubscribeRequest)(nil),      // 25: snmpproxy.v1.UnsubscribeRequest
	(*UnsubscribeResponse)(nil),     // 26: snmpproxy.v1.UnsubscribeResponse
	(*GetServerStatusRequest)(nil),  // 27: snmpproxy.v1.GetServerStatusRequest
	(*GetServerStatusResponse)(nil), // 28: snmpproxy.v1.GetServerStatusResponse
	(*GetSessionInfoRequest)(nil),   // 29: snmpproxy.v1.GetSessionInfoRequest
	(*GetSessionInfoResponse)(nil),  // 30: snmpproxy.v1.GetSessionInfoResponse
	(*UpdateTargetRequest)(nil),     // 31: snmpproxy.v1.UpdateTargetRequest
	(*UpdateTargetResponse)(nil),    // 32: snmpproxy.v1.UpdateTargetResponse
	(*GetConfigRequest)(nil),        // 33: snmpproxy.v1.GetConfigRequest
	(*GetConfigResponse)(nil),       // 34: snmpproxy.v1.GetConfigResponse
	(*SetConfigRequest)(nil),        // 35: snmpproxy.v1.SetConfigRequest
	(*SetConfigResponse)(nil),       // 36: snmpproxy.v1.SetConfigResponse
	(*RuntimeConfig)(nil),           // 37: snmpproxy.v1.RuntimeConfig
}
var file_snmpproxy_proto_depIdxs = []int32{
	10, // 0: snmpproxy.v1.Envelope.auth:type_name -> snmpproxy.v1.AuthRequest
	12, // 1: snmpproxy.v1.Envelope.monitor:type_name -> snmpproxy.v1.MonitorRequest
	14, // 2: snmpproxy.v1.Envelope.unmonitor:type_name -> snmpproxy.v1.UnmonitorRequest
	16, // 3: snmpproxy.v1.Envelope.list_targets:type_name -> snmpproxy.v1.ListTargetsRequest
	18, // 4: snmpproxy.v1.Envelope.get_target:type_name -> snmpproxy.v1.GetTargetRequest
	20, // 5: snmpproxy.v1.Envelope.get_history:type_name -> snmpproxy.v1.GetHistoryRequest
	23, // 6: snmpproxy.v1.Envelope.subscribe:type_name -> snmpproxy.v1.SubscribeRequest
	25, // 7: snmpproxy.v1.Envelope.unsubscribe:type_name -> snmpproxy.v1.UnsubscribeRequest
	27, // 8: snmpproxy.v1.Envelope.get_server_status:type_name -> snmpproxy.v1.GetServerStatusRequest
	29, // 9: snmpproxy.v1.Envelope.get_session_info:type_name -> snmpproxy.v1.GetSessionInfoRequest
	31, // 10: snmpproxy.v1.Envelope.update_target:type_name -> snmpproxy.v1.UpdateTargetRequest
	33, // 11: snmpproxy.v1.Envelope.get_config:type_name -> snmpproxy.v1.GetConfigRequest
	35, // 12: snmpproxy.v1.Envelope.set_config:type_name -> snmpproxy.v1.SetConfigRequest
	11, // 13: snmpproxy.v1.Envelope.auth_resp:type_name -> snmpproxy.v1.AuthResponse
	13, // 14: snmpproxy.v1.Envelope.monitor_resp:type_name -> snmpproxy.v1.MonitorResponse
	15, // 15: snmpproxy.v1.Envelope.unmonitor_resp:type_name -> snmpproxy.v1.UnmonitorResponse
	17, // 16: snmpproxy.v1.Envelope.list_targets_resp:type_name -> snmpproxy.v1.ListTargetsResponse
	19, // 17: snmpproxy.v1.Envelope.get_target_resp:type_name -> snmpproxy.v1.GetTargetResponse
	21, // 18: snmpproxy.v1.Envelope.get_history_resp:type_name -> snmpproxy.v1.GetHistoryResponse
	24, // 19: snmpproxy.v1.Envelope.subscribe_resp:type_name -> snmpproxy.v1.SubscribeResponse
	26, // 20: snmpproxy.v1.Envelope.unsubscribe_resp:type_name -> snmpproxy.v1.UnsubscribeResponse
	28, // 21: snmpproxy.v1.Envelope.get_server_status_resp:type_name -> snmpproxy.v1.GetServerStatusResponse
	30, // 22: snmpproxy.v1.Envelope.get_session_info_resp:type_name -> snmpproxy.v1.GetSessionInfoResponse
	32, // 23: snmpproxy.v1.Envelope.update_target_resp:type_name -> snmpproxy.v1.UpdateTargetResponse
	34, // 24: snmpproxy.v1.Envelope.get_config_resp:type_name -> snmpproxy.v1.GetConfigResponse
	36, // 25: snmpproxy.v1.Envelope.set_config_resp:type_name -> snmpproxy.v1.SetConfigResponse
	5,  // 26: snmpproxy.v1.Envelope.sample:type_name -> snmpproxy.v1.Sample
	4,  // 27: snmpproxy.v1.Envelope.error:type_name -> snmpproxy.v1.Error
	2,  // 28: snmpproxy.v1.SNMPv3.security_level:type_name -> snmpproxy.v1.SecurityLevel
	0,  // 29: snmpproxy.v1.SNMPv3.auth_protocol:type_name -> snmpproxy.v1.AuthProtocol
	1,  // 30: snmpproxy.v1.SNMPv3.priv_protocol:type_name -> snmpproxy.v1.PrivProtocol
	6,  // 31: snmpproxy.v1.SNMPConfig.v2c:type_name -> snmpproxy.v1.SNMPv2c
	7,  // 32: snmpproxy.v1.SNMPConfig.v3:type_name -> snmpproxy.v1.SNMPv3
	8,  // 33: snmpproxy.v1.MonitorRequest.snmp:type_name -> snmpproxy.v1.SNMPConfig
	9,  // 34: snmpproxy.v1.ListTargetsResponse.targets:type_name -> snmpproxy.v1.Target
	9,  // 35: snmpproxy.v1.GetTargetResponse.target:type_name -> snmpproxy.v1.Target
	22, // 36: snmpproxy.v1.GetHistoryResponse.history:type_name -> snmpproxy.v1.TargetHistory
	5,  // 37: snmpproxy.v1.TargetHistory.samples:type_name -> snmpproxy.v1.Sample
	9,  // 38: snmpproxy.v1.UpdateTargetResponse.target:type_name -> snmpproxy.v1.Target
	37, // 39: snmpproxy.v1.GetConfigResponse.config:type_name -> snmpproxy.v1.RuntimeConfig
	37, // 40: snmpproxy.v1.SetConfigResponse.config:type_name -> snmpproxy.v1.RuntimeConfig
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_snmpproxy_proto_init() }
func file_snmpproxy_proto_init() {
	if File_snmpproxy_proto != nil {
		return
	}
	file_snmpproxy_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Auth)(nil),
		(*Envelope_Monitor)(nil),
		(*Envelope_Unmonitor)(nil),
		(*Envelope_ListTargets)(nil),
		(*Envelope_GetTarget)(nil),
		(*Envelope_GetHistory)(nil),
		(*Envelope_Subscribe)(nil),
		(*Envelope_Unsubscribe)(nil),
		(*Envelope_GetServerStatus)(nil),
		(*Envelope_GetSessionInfo)(nil),
		(*Envelope_UpdateTarget)(nil),
		(*Envelope_GetConfig)(nil),
		(*Envelope_SetConfig)(nil),
		(*Envelope_AuthResp)(nil),
		(*Envelope_MonitorResp)(nil),
		(*Envelope_UnmonitorResp)(nil),
		(*Envelope_ListTargetsResp)(nil),
		(*Envelope_GetTargetResp)(nil),
		(*Envelope_GetHistoryResp)(nil),
		(*Envelope_SubscribeResp)(nil),
		(*Envelope_UnsubscribeResp)(nil),
		(*Envelope_GetServerStatusResp)(nil),
		(*Envelope_GetSessionInfoResp)(nil),
		(*Envelope_UpdateTargetResp)(nil),
		(*Envelope_GetConfigResp)(nil),
		(*Envelope_SetConfigResp)(nil),
		(*Envelope_Sample)(nil),
		(*Envelope_Error)(nil),
	}
	file_snmpproxy_proto_msgTypes[5].OneofWrappers = []any{
		(*SNMPConfig_V2C)(nil),
		(*SNMPConfig_V3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snmpproxy_proto_rawDesc), len(file_snmpproxy_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snmpproxy_proto_goTypes,
		DependencyIndexes: file_snmpproxy_proto_depIdxs,
		EnumInfos:         file_snmpproxy_proto_enumTypes,
		MessageInfos:      file_snmpproxy_proto_msgTypes,
	}.Build()
	File_snmpproxy_proto = out.File
	file_snmpproxy_proto_goTypes = nil
	file_snmpproxy_proto_depIdxs = nil
}
